-- CREATE DATABASE AND SCHEMA
CREATE DATABASE PROJECT_14A_DB;
USE DATABASE PROJECT_14A_DB;
CREATE SCHEMA ECOMMERCE_ANALYTICS;
USE SCHEMA ECOMMERCE_ANALYTICS;

--CREATE TABLE 
CREATE OR REPLACE TABLE LAKE_RAW_EVENTS(
RAW_EVENT VARIANT
);

--CREATE STAGING
CREATE OR REPLACE STAGE ECOMMERCE_RAW_STAGE;
COPY INTO LAKE_RAW_EVENTS FROM @ECOMMERCE_RAW_STAGE 
FILE_FORMAT=(
TYPE=JSON 
);

--COPY INTO LAKE_RAW_EVENTS 
COPY INTO LAKE_RAW_EVENTS FROM @ECOMMERCE_RAW_STAGE/batch1.json 
FILE_FORMAT=(
TYPE=JSON 
)
ON_ERROR='ABORT_STATEMENT';
COPY INTO LAKE_RAW_EVENTS FROM @ECOMMERCE_RAW_STAGE/batch2.json 
FILE_FORMAT=(
TYPE=JSON 
)
ON_ERROR='ABORT_STATEMENT';
SELECT COUNT(*) AS TOTAL_RAW_RECORD_CT FROM LAKE_RAW_EVENTS; 
COPY INTO LAKE_RAW_EVENTS
FROM @ECOMMERCE_RAW_STAGE/batch3.json
FILE_FORMAT = (
    TYPE = JSON
)
ON_ERROR = 'CONTINUE'; 
SELECT COUNT(*) AS TOTAL_RAW_RECORD_CT FROM LAKE_RAW_EVENTS;

-- EXTRACT JSON FIELDS 
SELECT RAW_EVENT:event_id::STRING AS EVENT_ID,
RAW_EVENT:timestamp::TIMESTAMP AS EVENT_TIME,
RAW_EVENT:user_id:NUMBER AS USER_ID,
RAW_EVENT:action::STRING AS ACTION,
RAW_EVENT:order:total::NUMBER(12,2) AS ORDER_TOTAL,
RAW_EVENT:promo_code::STRING AS PROMO_CODE FROM LAKE_RAW_EVENTS 
ORDER BY EVENT_TIME;

--CALCULATE NET REVENUE 
SELECT RAW_EVENT:event_id::STRING AS EVENT_ID,
RAW_EVENT:order:total::NUMBER(12,2) AS ORDER_TOTAL,
RAW_EVENT:order:shipping_cost::NUMBER(12,2) AS SHIPPPING_COST,
RAW_EVENT:order:tax::NUMBER(12,2) AS TAX,
COALESCE(
RAW_EVENT:discount_amount::NUMBER(12,2),0
) AS DISCOUNT_AMOUNT,
(
RAW_EVENT:order:total::NUMBER(12,2)
-RAW_EVENT:order:shipping_cost::NUMBER(12,2)
-RAW_EVENT:order:tax::NUMBER(12,2)
-COALESCE(
RAW_EVENT:discount_amount::NUMBER(12,2),0
)
) AS NET_REVENUE FROM LAKE_RAW_EVENTS 
WHERE RAW_EVENT:order:total::NUMBER(12,2)>0 ORDER BY EVENT_ID;

-- CALCULATE FUNNEL KPIs
SELECT
    COUNT(*) AS TOTAL_EVENTS,

    COUNT_IF(
        RAW_EVENT:action::STRING = 'purchase'
        AND RAW_EVENT:order:total::NUMBER(12,2) > 0
    ) AS TOTAL_PURCHASES,

    ROUND(
        COUNT_IF(
            RAW_EVENT:action::STRING = 'purchase'
            AND RAW_EVENT:order:total::NUMBER(12,2) > 0
        ) * 100.0 / COUNT(*),
        2
    ) AS CONVERSION_RATE_PCT,

    SUM(
        CASE
            WHEN RAW_EVENT:action::STRING = 'purchase'
                 AND RAW_EVENT:order:total::NUMBER(12,2) > 0
            THEN RAW_EVENT:order:total::NUMBER(12,2)
            ELSE 0
        END
    ) AS TOTAL_GROSS_REVENUE,

    ROUND(
        SUM(
            CASE
                WHEN RAW_EVENT:action::STRING = 'purchase'
                     AND RAW_EVENT:order:total::NUMBER(12,2) > 0
                THEN RAW_EVENT:order:total::NUMBER(12,2)
                ELSE 0
            END
        )
        /
        NULLIF(
            COUNT_IF(
                RAW_EVENT:action::STRING = 'purchase'
                AND RAW_EVENT:order:total::NUMBER(12,2) > 0
            ),
            0
        ),
        2
    ) AS AVERAGE_ORDER_VALUE

FROM LAKE_RAW_EVENTS;

--CREATE WAREHOUSE TABLE
CREATE OR REPLACE TABLE DW_STRUCTURED_EVENTS(
EVENT_ID VARCHAR,
EVENT_TIME TIMESTAMP,
USER_ID NUMBER,
PAGE VARCHAR,
ACTION VARCHAR,
ORDER_TOTAL NUMBER(12,2),
SHIPPING_COST NUMBER(12,2),
TAX NUMBER(12,2),
ITEMS NUMBER,
PROMO_CODE VARCHAR,
DISCOUNT_AMOUNT NUMBER(12,2),
NET_REVENUE NUMBER(12,2)
);
INSERT INTO DW_STRUCTURED_EVENTS(
EVENT_ID,
EVENT_TIME,
USER_ID,
PAGE,
ACTION,
ORDER_TOTAL,
SHIPPING_COST,
TAX,
ITEMS,
PROMO_CODE,
DISCOUNT_AMOUNT,
NET_REVENUE
)
SELECT RAW_EVENT:event_id::VARCHAR,
RAW_EVENT:timestamp::TIMESTAMP,
RAW_EVENT:user_id::NUMBER,
RAW_EVENT:page::VARCHAR,
RAW_EVENT:action::VARCHAR,
RAW_EVENT:order:total::NUMBER(12,2),
RAW_EVENT:order:shipping_cost::NUMBER(12,2),
RAW_EVENT:order:tax::NUMBER(12,2),
RAW_EVENT:order:items::NUMBER,
RAW_EVENT:promo_code::VARCHAR,
COALESCE(
RAW_EVENT:discount_amount::NUMBER(12,2),0
),
CASE WHEN RAW_EVENT:order:total::NUMBER(12,2)>0 
THEN RAW_EVENT:order:total::NUMBER(12,2) 
- COALESCE(
RAW_EVENT:order:shipping_cost::NUMBER(12,2),0
)
- COALESCE(
RAW_EVENT:order:tax::NUMBER(12,2),0 
)
- COALESCE(
RAW_EVENT:discount_amount::NUMBER(12,2),0
)
ELSE 0 
END 
FROM LAKE_RAW_EVENTS;
SELECT COUNT(*) AS STORED_RECORDS_QTY,SUM(NET_REVENUE) AS TOTAL_NET_REVENUE 
FROM DW_STRUCTURED_EVENTS;

-- CREATE QUARANTINE TABLE 
CREATE OR REPLACE TABLE QUARANTINE_RAW_EVENTS(
QUARANTINE_ID NUMBER AUTOINCREMENT,
RAW_RECORD_TEXT VARCHAR,
REASON VARCHAR
);
INSERT INTO QUARANTINE_RAW_EVENTS(
RAW_RECORD_TEXT,
REASON
)
VALUES(
'INVALID_JSON_PAYLOAD_MALFORMED_STRING','MALFORMED_JSON_BODY'
);
SELECT * FROM QUARANTINE_RAW_EVENTS;

-- WAREHOUSE ACTION SUMMARY 
SELECT ACTION,COUNT(*) AS EVENT_COUNT FROM DW_STRUCTURED_EVENTS GROUP BY ACTION 
ORDER BY ACTION;