 --CREATE DATABASE AND SCHEMA 
 CREATE DATABASE HEALTHCARE_PIPELINE_DB;
 USE HEALTHCARE_PIPELINE_DB;
 CREATE SCHEMA CLAIMS_CORE;
 USE SCHEMA CLAIMS_CORE;

 --CREATE BRONZE TABLE
 CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS(
INGEST_ID NUMBER AUTOINCREMENT,
PAYLOAD VARIANT,
LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
 );

 CREATE OR REPLACE STAGE CLAIMS_RAW_STAGE 
 FILE_FORMAT=(
TYPE=JSON
 );

LIST @CLAIMS_RAW_STAGE;

COPY INTO BRONZE_RAW_CLAIMS(PAYLOAD) FROM @CLAIMS_RAW_STAGE 
FILE_FORMAT=(
TYPE=JSON 
)
ON_ERROR='CONTINUE';

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_RAW_CLAIMS;

CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS(
QUARANTINE_ID NUMBER AUTOINCREMENT,
RAW_RECORD_TEXT VARCHAR,
REASON VARCHAR
);

SELECT INGEST_ID,PAYLOAD FROM BRONZE_RAW_CLAIMS ORDER BY INGEST_ID;

SELECT TRY_PARSE_JSON('INVALID_PAYLOAD_UNPARSEABLE') AS PARSED_PAYLOAD;

INSERT INTO QUARANTINE_CLAIMS_PAYLOADS(
RAW_RECORD_TEXT,REASON 
)
SELECT 'INVALID_PAYLOAD_UNPARSEABLE_STRING','MALFORMED_JSON_BODY'
WHERE TRY_PARSE_JSON('INVALID_PAYLOAD_UNPARSEABLE_STRING') IS NULL;

SELECT * FROM QUARANTINE_CLAIMS_PAYLOADS;

CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS;
SHOW STREAMS;

CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS(
CLAIM_ID VARCHAR,
SUBMITTED_AT TIMESTAMP_TZ,
PATIENT_ID NUMBER,
PROVIDER_ID VARCHAR,
DIAGNOSIS_CODE VARCHAR,
BILLED_AMOUNT NUMBER(18,2),
COPAY_AMOUNT NUMBER(18,2),
NET_PAYABLE_AMOUNT NUMBER(18,2),
STATUS VARCHAR
);

INSERT INTO SILVER_CLAIMS_TRANSACTIONS(
CLAIM_ID,
SUBMITTED_AT,
PATIENT_ID,
PROVIDER_ID,
DIAGNOSIS_CODE,
BILLED_AMOUNT,
COPAY_AMOUNT,
NET_PAYABLE_AMOUNT,
STATUS
)
SELECT CLAIM_ID,SUBMITTED_AT,PATIENT_ID,PROVIDER_ID,DIAGNOSIS_CODE,BILLED_AMOUNT,
COPAY_AMOUNT,BILLED_AMOUNT - COPAY_AMOUNT AS NET_PAYABLE_AMOUNT, STATUS 
FROM (
SELECT PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
PAYLOAD:billed_amount::NUMBER(18,2) AS BILLED_AMOUNT,
PAYLOAD:copay_amount::NUMBER(18,2) AS COPAY_AMOUNT,
PAYLOAD:status::VARCHAR AS STATUS,
ROW_NUMBER() OVER (
PARTITION BY PAYLOAD:claim_id::VARCHAR 
ORDER BY INGEST_ID DESC 
) AS RN FROM BRONZE_RAW_CLAIMS 
)
WHERE RN=1;

SELECT * FROM SILVER_CLAIMS_TRANSACTIONS ORDER BY CLAIM_ID;

INSERT INTO BRONZE_RAW_CLAIMS (PAYLOAD) 
SELECT PARSE_JSON(
'{
"claim_id":"CLM-301",
"submitted_at":"2026-08-10T08:00:00Z",
"patient_id":5001,
"provider_id":"PRV-10",
"diagnosis_code":"ICD-10-A",
"billed_amount":15000.00,
"copay_amount":500.00,
"status":"APPROVED"
}'
);

SELECT * FROM STRM_BRONZE_CLAIMS;

MERGE INTO SILVER_CLAIMS_TRANSACTIONS AS TARGET 
USING (
SELECT 
PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
PAYLOAD:billed_amount::NUMBER(18,2) AS BILLED_AMOUNT,
PAYLOAD:copay_amount::NUMBER(18,2) AS COPAY_AMOUNT,
PAYLOAD:billed_amount::NUMBER(18,2) - PAYLOAD:copay_amount::NUMBER(18,2) AS NET_PAYABLE_AMOUNT,
PAYLOAD:status::VARCHAR AS STATUS FROM STRM_BRONZE_CLAIMS 
QUALIFY ROW_NUMBER() OVER (
PARTITION BY PAYLOAD:claim_id::VARCHAR 
ORDER BY METADATA$ROW_ID DESC 
) = 1 
) AS SOURCE 
ON TARGET.CLAIM_ID = SOURCE.CLAIM_ID 
WHEN MATCHED THEN UPDATE SET 
TARGET.SUBMITTED_AT=SOURCE.SUBMITTED_AT,
TARGET.PATIENT_ID=SOURCE.PATIENT_ID,
TARGET.PROVIDER_ID=SOURCE.PROVIDER_ID,
TARGET.DIAGNOSIS_CODE=SOURCE.DIAGNOSIS_CODE,
TARGET.BILLED_AMOUNT=SOURCE.BILLED_AMOUNT,
TARGET.COPAY_AMOUNT=SOURCE.COPAY_AMOUNT,
TARGET.NET_PAYABLE_AMOUNT=SOURCE.NET_PAYABLE_AMOUNT,
TARGET.STATUS=SOURCE.STATUS
WHEN NOT MATCHED THEN INSERT(
CLAIM_ID,
SUBMITTED_AT,
PATIENT_ID,
PROVIDER_ID,
DIAGNOSIS_CODE,
BILLED_AMOUNT,
COPAY_AMOUNT,
NET_PAYABLE_AMOUNT,
STATUS
)
VALUES (
SOURCE.CLAIM_ID,
SOURCE.SUBMITTED_AT,
SOURCE.PATIENT_ID,
SOURCE.PROVIDER_ID,
SOURCE.DIAGNOSIS_CODE,
SOURCE.BILLED_AMOUNT,
SOURCE.COPAY_AMOUNT,
SOURCE.NET_PAYABLE_AMOUNT,
SOURCE.STATUS
);

SELECT * FROM SILVER_CLAIMS_TRANSACTIONS ORDER BY CLAIM_ID; 

CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY 
TARGET_LAG='1 minute'
WAREHOUSE=COMPUTE_WH 
AS 
SELECT 
PROVIDER_ID,
SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
SUM(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
COUNT(*) AS APPROVED_CLAIMS FROM SILVER_CLAIMS_TRANSACTIONS 
WHERE STATUS='APPROVED' GROUP BY PROVIDER_ID;

SELECT * FROM DT_PROVIDER_FINANCIAL_SUMMARY ORDER BY PROVIDER_ID;

SELECT
    NAME AS DYNAMIC_TABLE_NAME,
    REFRESH_ACTION,
    STATE,
    REFRESH_TRIGGER,
    REFRESH_START_TIME,
    REFRESH_END_TIME
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
        NAME => 'HEALTHCARE_PIPELINE_DB.CLAIMS_CORE.DT_PROVIDER_FINANCIAL_SUMMARY'
    )
)
ORDER BY REFRESH_START_TIME DESC;

SELECT
    NAME AS DYNAMIC_TABLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUALIFIED_NAME,
    INPUTS,
    TARGET_LAG_TYPE,
    TARGET_LAG_SEC,
    SCHEDULING_STATE,
    ALTER_TRIGGER
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_GRAPH_HISTORY()
)
WHERE NAME = 'DT_PROVIDER_FINANCIAL_SUMMARY';

SELECT
    INGEST_ID,
    PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
    PAYLOAD:billed_amount::NUMBER(18,2) AS BILLED_AMOUNT,
    PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;

DELETE FROM BRONZE_RAW_CLAIMS
WHERE INGEST_ID = (
    SELECT MAX(INGEST_ID)
    FROM BRONZE_RAW_CLAIMS
    WHERE PAYLOAD:claim_id::VARCHAR = 'CLM-301'
);

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_RAW_CLAIMS;

SELECT
    INGEST_ID,
    PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
    PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;

SELECT
    SUM(PAYLOAD:billed_amount::NUMBER(18,2)) AS BRONZE_GROSS_TOTAL
FROM BRONZE_RAW_CLAIMS;

SELECT
    (
        SELECT SUM(PAYLOAD:billed_amount::NUMBER(18,2))
        FROM BRONZE_RAW_CLAIMS
    ) AS BRONZE_GROSS_TOTAL,

    (
        SELECT SUM(BILLED_AMOUNT)
        FROM SILVER_CLAIMS_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,

    (
        SELECT SUM(TOTAL_BILLED_AMOUNT)
        FROM DT_PROVIDER_FINANCIAL_SUMMARY
    ) AS GOLD_GROSS_TOTAL;

SELECT
    (
        SELECT SUM(PAYLOAD:billed_amount::NUMBER(18,2))
        FROM BRONZE_RAW_CLAIMS
    ) AS BRONZE_GROSS_TOTAL,

    (
        SELECT SUM(BILLED_AMOUNT)
        FROM SILVER_CLAIMS_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,

    (
        SELECT SUM(TOTAL_BILLED_AMOUNT)
        FROM DT_PROVIDER_FINANCIAL_SUMMARY
    ) AS GOLD_GROSS_TOTAL,

    CASE
        WHEN
            (
                SELECT SUM(BILLED_AMOUNT)
                FROM SILVER_CLAIMS_TRANSACTIONS
            ) = 197700.00
            AND
            (
                SELECT SUM(TOTAL_BILLED_AMOUNT)
                FROM DT_PROVIDER_FINANCIAL_SUMMARY
            ) = 152700.00
            AND
            (
                SELECT COUNT(*)
                FROM SILVER_CLAIMS_TRANSACTIONS
            ) = 6
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG;