CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH WITH
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE RETAIL_WH;

CREATE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
NULL_IF=('NULL','null');

CREATE STAGE RETAIL_STAGE FILE_FORMAT=CSV_FORMAT;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INTEGER,
CUSTOMER_NAME VARCHAR,
CITY VARCHAR,
MEMBERSHIP VARCHAR
);

CREATE TABLE PRODUCTS(
PRODUCT_ID INTEGER,
PRODUCT_NAME VARCHAR,
CATEGORY VARCHAR,
PRICE NUMBER(10,2)
);

CREATE TABLE BRANCHES(
BRANCH_ID INTEGER,
BRANCH_NAME VARCHAR,
CITY VARCHAR
);

CREATE TABLE SALES(
SALE_ID INTEGER,
CUSTOMER_ID INTEGER,
PRODUCT_ID INTEGER,
BRANCH_ID INTEGER,
QUANTITY INTEGER,
SALE_DATE DATE,
TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS FROM @RETAIL_STAGE/customers.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO PRODUCTS FROM @RETAIL_STAGE/products.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO BRANCHES FROM @RETAIL_STAGE/branches.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO SALES FROM @RETAIL_STAGE/sales.csv FILE_FORMAT=CSV_FORMAT;

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM BRANCHES;
SELECT * FROM SALES;

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES;

SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.MEMBERSHIP,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID=S.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME,C.MEMBERSHIP 
ORDER BY TOTAL_SPENDING DESC;

SELECT B.BRANCH_ID,B.BRANCH_NAME,B.CITY,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM BRANCHES B 
JOIN SALES S ON B.BRANCH_ID=S.BRANCH_ID GROUP BY B.BRANCH_ID,B.BRANCH_NAME,B.CITY ORDER BY TOTAL_REVENUE DESC;

SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(S.QUANTITY) AS TOTAL_QUANTITY_SOLD,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS P 
JOIN SALES S ON P.PRODUCT_ID=S.PRODUCT_ID GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME ORDER BY TOTAL_REVENUE DESC;

SELECT P.CATEGORY,SUM(S.QUANTITY) AS TOTAL_QUANTITY_SOLD,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS P 
JOIN SALES S ON P.PRODUCT_ID=S.PRODUCT_ID GROUP BY P.CATEGORY ORDER BY TOTAL_REVENUE DESC;
--HIGHEST REVENUE BRANCH
SELECT B.BRANCH_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM BRANCHES B JOIN SALES S ON B.BRANCH_ID=S.BRANCH_ID
GROUP BY B.BRANCH_NAME ORDER BY TOTAL_REVENUE DESC LIMIT 1;
--HIGHEST SPENDING CUSTOMER
SELECT C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS C JOIN SALES S ON C.CUSTOMER_ID=S.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME ORDER BY TOTAL_SPENDING DESC LIMIT 1;
--TOP 3 PRODUCTS
SELECT P.PRODUCT_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS P JOIN SALES S ON P.PRODUCT_ID=S.PRODUCT_ID
GROUP BY P.PRODUCT_NAME ORDER BY TOTAL_REVENUE DESC LIMIT 3;
--TOP 3 CUSTOMERS
SELECT C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS C JOIN SALES S ON C.CUSTOMER_ID=S.CUSTOMER_ID 
GROUP BY C.CUSTOMER_NAME ORDER BY TOTAL_SPENDING DESC LIMIT 3;
--RANK CUSTOMERS
SELECT C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,RANK() OVER(
ORDER BY SUM(S.TOTAL_AMOUNT) DESC 
) AS CUSTOMER_RANK FROM CUSTOMERS C JOIN SALES S ON C.CUSTOMER_ID=S.CUSTOMER_ID GROUP BY C.CUSTOMER_NAME ORDER BY CUSTOMER_RANK;

--RANK BRANCHES
SELECT B.BRANCH_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,RANK() OVER(
ORDER BY SUM(S.TOTAL_AMOUNT) DESC 
) AS BRANCH_RANK FROM BRANCHES B JOIN SALES S ON B.BRANCH_ID=S.BRANCH_ID GROUP BY B.BRANCH_NAME ORDER BY BRANCH_RANK;

--TOP SELLING PRODUCT IN EACH CATEGORY
WITH PRODUCT_REVENUE AS (
SELECT P.CATEGORY,P.PRODUCT_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS P JOIN SALES S ON P.PRODUCT_ID=S.PRODUCT_ID 
GROUP BY P.CATEGORY,P.PRODUCT_NAME 
),
RANKED_PRODUCTS AS(
SELECT CATEGORY,PRODUCT_NAME,TOTAL_REVENUE,ROW_NUMBER() OVER(
PARTITION BY CATEGORY ORDER BY TOTAL_REVENUE DESC
) AS RN FROM PRODUCT_REVENUE
)
SELECT CATEGORY,PRODUCT_NAME,TOTAL_REVENUE FROM RANKED_PRODUCTS WHERE RN=1;

--CUMULATIVE SALES
SELECT SALE_DATE,SALE_ID,TOTAL_AMOUNT,SUM(TOTAL_AMOUNT) OVER(
ORDER BY SALE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW 
) AS CUMULATIVE_SALES FROM SALES ORDER BY SALE_DATE;

--AVG SALE AMOUNT
SELECT SALE_ID,SALE_DATE,TOTAL_AMOUNT,AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT FROM SALES ORDER BY SALE_DATE;

--CUSTOMER-WISE REVENUE USING CTE
WITH CUSTOMER_REVENUE AS(
SELECT CUSTOMER_ID,SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES GROUP BY CUSTOMER_ID
)
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,CR.TOTAL_REVENUE FROM CUSTOMER_REVENUE CR JOIN CUSTOMERS C ON CR.CUSTOMER_ID=C.CUSTOMER_ID 
ORDER BY CR.TOTAL_REVENUE DESC;

--CUSTOMERS SPENDING ABOVE AVG
WITH CUSTOMER_SPENDING AS (
SELECT CUSTOMER_ID,SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING FROM SALES GROUP BY CUSTOMER_ID 
),
AVERAGE_SPENDING AS (
SELECT AVG(TOTAL_SPENDING) AS AVG_SPENDING FROM CUSTOMER_SPENDING
)
SELECT C.CUSTOMER_NAME,CS.TOTAL_SPENDING FROM CUSTOMER_SPENDING CS JOIN CUSTOMERS C ON CS.CUSTOMER_ID=C.CUSTOMER_ID
CROSS JOIN AVERAGE_SPENDING A WHERE CS.TOTAL_SPENDING>A.AVG_SPENDING ORDER BY CS.TOTAL_SPENDING DESC;

--SALES_REPORT AS VIEW
CREATE VIEW SALES_REPORT AS 
SELECT S.SALE_ID,S.SALE_DATE,C.CUSTOMER_NAME,C.MEMBERSHIP,P.PRODUCT_NAME,P.CATEGORY,B.BRANCH_NAME,B.CITY AS BRANCH_CITY,
S.QUANTITY,S.TOTAL_AMOUNT FROM SALES S JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID JOIN BRANCHES B ON S.BRANCH_ID=B.BRANCH_ID;
SELECT * FROM SALES_REPORT;

--TOP CUSTOMERS AS MATERIALIZED VIEW
CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS 
SELECT CUSTOMER_ID,SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING FROM SALES GROUP BY CUSTOMER_ID;
SELECT * FROM TOP_CUSTOMERS ORDER BY TOTAL_SPENDING DESC;

Github link: https://github.com/fulpati/Retail-Analytics-snowflake-prj2