CREATE WAREHOUSE ENTERPRISE_WH WITH 
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE ENTERPRISE_WH;

CREATE DATABASE ENTERPRISE_DB;

CREATE SCHEMA ENTERPRISE_DB.SALES_SCHEMA;

USE DATABASE ENTERPRISE_DB;
USE SCHEMA SALES_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
NULL_IF=('NULL','null');

CREATE STAGE SALES_STAGE FILE_FORMAT=CSV_FORMAT;

LIST @SALES_STAGE;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
CITY VARCHAR,
MEMBERSHIP VARCHAR 
);

CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR,
CATEGORY VARCHAR,
PRICE NUMBER(10,2)
);

CREATE TABLE BRANCHES(
BRANCH_ID NUMBER,
BRANCH_NAME VARCHAR,
STATE VARCHAR 
);

CREATE TABLE SALES(
SALE_ID NUMBER,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
BRANCH_ID NUMBER,
QUANTITY NUMBER,
SALE_DATE DATE,
TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS FROM @SALES_STAGE/customers.csv
FILE_FORMAT=(FORMAT_NAME=CSV_FORMAT);

COPY INTO PRODUCTS FROM @SALES_STAGE/products.csv
FILE_FORMAT=(FORMAT_NAME=CSV_FORMAT);

COPY INTO BRANCHES FROM @SALES_STAGE/branches.csv 
FILE_FORMAT=(FORMAT_NAME=CSV_FORMAT);

COPY INTO SALES FROM @SALES_STAGE/sales_history.csv 
FILE_FORMAT=(FORMAT_NAME=CSV_FORMAT);

CREATE OR REPLACE STREAM SALES_STREAM ON TABLE SALES;
SHOW STREAMS;

LIST @SALES_STAGE;

CREATE OR REPLACE TABLE NEW_SALES(
SALE_ID NUMBER,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
BRANCH_ID NUMBER,
QUANTITY NUMBER,
SALE_DATE DATE,
TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO NEW_SALES FROM @SALES_STAGE/new_sales.csv 
FILE_FORMAT=(FORMAT_NAME=CSV_FORMAT);

SELECT * FROM NEW_SALES ORDER BY SALE_ID;

INSERT INTO SALES SELECT * FROM NEW_SALES;
SELECT * FROM SALES ORDER BY SALE_ID;
SELECT COUNT(*) AS TOTAL_RECORDS FROM SALES;

--DISPLAY NEWLY INSERTED RECORDS
SELECT SALE_ID,CUSTOMER_ID,PRODUCT_ID,BRANCH_ID,QUANTITY,SALE_DATE,TOTAL_AMOUNT,
METADATA$ACTION,METADATA$ISUPDATE FROM SALES_STREAM ORDER BY SALE_ID;

--IDENTIFY DUPLICATE SALE IDS
SELECT SALE_ID,COUNT(*) AS RECORD_COUNT FROM SALES GROUP BY SALE_ID HAVING COUNT(*)>1;

--IDENTIFY MISSING CUSTOMER IDS
SELECT DISTINCT S.CUSTOMER_ID FROM SALES S LEFT JOIN CUSTOMERS C 
ON S.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL;

--display invalid product IDs
SELECT DISTINCT S.PRODUCT_ID FROM SALES S LEFT JOIN PRODUCTS P 
ON S.PRODUCT_ID=P.PRODUCT_ID WHERE P.PRODUCT_ID IS NULL;

--COUNT NEWLY INSERTED RECORDS
SELECT COUNT(*) AS NEWLY_INSERTED_RECORDS FROM SALES WHERE SALE_ID>5;

SELECT * FROM SALES ORDER BY SALE_ID;
--DELETE ONE RECORD
DELETE FROM SALES WHERE SALE_ID=10;
SELECT * FROM SALES WHERE SALE_ID=10;
--RECOVER SALE ID 10 USING TIME TRAVEL
-- SELECT LAST_QUERY_ID(-2) AS DELETE_QUERY_ID;
-- SET DELETE_QUERY_ID=(SELECT LAST_QUERY_ID(-2));
-- SELECT $DELETE_QUERY_ID;
-- SELECT * FROM SALES BEFORE (STATEMENT=> $DELETE_QUERY_ID) WHERE SALE_ID=10;
SELECT QUERY_ID,QUERY_TEXT,START_TIME FROM TABLE(
INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION()) WHERE QUERY_TEXT ILIKE 'DELETE FROM SALES WHERE SALE_ID=10%' ORDER BY START_TIME DESC;
SELECT * FROM SALES BEFORE( STATEMENT=>'01c68e09-3203-3107-0017-fb060005952a') WHERE SALE_ID=10;
INSERT INTO SALES SELECT * FROM SALES BEFORE(STATEMENT=>'01c68e09-3203-3107-0017-fb060005952a') WHERE SALE_ID=10;
SELECT * FROM SALES WHERE SALE_ID=10;
SELECT COUNT(*) AS TOTAL_SALES FROM SALES;
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES;

--zero copy clone
CREATE OR REPLACE TABLE SALES_TEST CLONE SALES;
SELECT * FROM SALES_TEST ORDER BY SALE_ID;
SELECT COUNT(*) AS CLONE_RECORD_COUNT FROM SALES_TEST;
-- INSERT 1 NEW RECORD INTO CLONE
INSERT INTO SALES_TEST(
SALE_ID,CUSTOMER_ID,PRODUCT_ID,BRANCH_ID,QUANTITY,SALE_DATE,TOTAL_AMOUNT
) VALUES(
11,1,105,1,1,'2026-07-11',12000
);
SELECT * FROM SALES_TEST WHERE SALE_ID=11;
--CHECK IF ORIGINAL SALES IN UNCHANGED
SELECT COUNT(*) AS SALES_COUNT FROM SALES;
SELECT COUNT(*) AS SALES_TEST_COUNT FROM SALES_TEST;

--CREATE TASK
CREATE OR REPLACE TASK DAILY_SALES_INCREMENTAL_LOAD WAREHOUSE=ENTERPRISE_WH
SCHEDULE='USING CRON 0 0 * * * UTC' AS
MERGE INTO SALES AS TARGET USING NEW_SALES AS SOURCE 
ON TARGET.SALE_ID=SOURCE.SALE_ID 
WHEN MATCHED THEN UPDATE SET
TARGET.CUSTOMER_ID=SOURCE.CUSTOMER_ID,
TARGET.PRODUCT_ID=SOURCE.PRODUCT_ID,
TARGET.BRANCH_ID=SOURCE.BRANCH_ID,
TARGET.QUANTITY=SOURCE.QUANTITY,
TARGET.SALE_DATE=SOURCE.SALE_DATE,
TARGET.TOTAL_AMOUNT=SOURCE.TOTAL_AMOUNT
WHEN NOT MATCHED THEN INSERT(
SALE_ID,CUSTOMER_ID,PRODUCT_ID,BRANCH_ID,QUANTITY,SALE_DATE,TOTAL_AMOUNT
) VALUES (
SOURCE.SALE_ID,SOURCE.CUSTOMER_ID,SOURCE.PRODUCT_ID,SOURCE.BRANCH_ID,
SOURCE.QUANTITY,SOURCE.SALE_DATE,SOURCE.TOTAL_AMOUNT
);

--RESUME TASK
ALTER TASK DAILY_SALES_INCREMENTAL_LOAD RESUME;
SHOW TASKS;
--FOR MANUAL EXCUTION
EXECUTE TASK DAILY_SALES_INCREMENTAL_LOAD;

--VERIFY TASK EXECUTION
SELECT NAME,STATE,SCHEDULED_TIME,COMPLETED_TIME,ERROR_MESSAGE FROM TABLE(
INFORMATION_SCHEMA.TASK_HISTORY(
TASK_NAME=>'DAILY_SALES_INCREMENTAL_LOAD',
RESULT_LIMIT=>10
)
) ORDER BY SCHEDULED_TIME DESC;
-- CHECK IF MERGE HAS CREATED ANY DUPLICATES
SELECT SALE_ID,COUNT(*) AS RECORD_COUNT FROM SALES GROUP BY SALE_ID 
HAVING COUNT(*)>1;
SELECT COUNT(*) AS TOTAL_SALES FROM SALES;

--BUSINEES ANALYTICS: CUSTOMER REVENUE REPORT
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP 
ORDER BY TOTAL_REVENUE DESC;

--BRANCH REVENUE REPORT
SELECT B.BRANCH_ID,B.BRANCH_NAME,B.STATE,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN BRANCHES B ON S.BRANCH_ID=B.BRANCH_ID GROUP BY B.BRANCH_ID,B.BRANCH_NAME,B.STATE 
ORDER BY TOTAL_REVENUE DESC;

--PRODUCT REVENUE REPORT
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY ORDER BY TOTAL_REVENUE DESC;

--MONTHLY REVENUE REPORT
SELECT DATE_TRUNC('MONTH',SALE_DATE) AS SALES_MONTH,SUM(TOTAL_AMOUNT) AS MONTHLY_REVENUE FROM SALES 
GROUP BY DATE_TRUNC('MONTH',SALE_DATE) ORDER BY SALES_MONTH;

--HIGHEST REVENUE CUSTOMER
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME 
ORDER BY TOTAL_REVENUE DESC LIMIT 1;

--HIGEST REVENUE BRANCH
SELECT B.BRANCH_ID,B.BRANCH_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN BRANCHES B ON S.BRANCH_ID=B.BRANCH_ID GROUP BY B.BRANCH_ID,B.BRANCH_NAME 
ORDER BY TOTAL_REVENUE DESC LIMIT 1;

--TOP 5 PRODUCTS 
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC LIMIT 5;

--CUSTOMER PURCHASE FREQUENCY
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,COUNT(S.SALE_ID) AS PURCHASE_FREQUENCY FROM SALES S 
JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME 
ORDER BY PURCHASE_FREQUENCY DESC;

--RUNNING REVENUE
SELECT SALE_ID,SALE_DATE,TOTAL_AMOUNT,SUM(TOTAL_AMOUNT) OVER (
ORDER BY SALE_DATE,SALE_ID
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW 
) AS RUNNING_REVENUE FROM SALES ORDER BY SALE_DATE,SALE_ID;

--CUSTOMER RANKING
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,RANK() OVER (
ORDER BY SUM(S.TOTAL_AMOUNT) DESC 
) AS CUSTOMER_RANK FROM SALES S JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID 
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME ORDER BY CUSTOMER_RANK;

--CUSTOMER_REVENUE VIEW
CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS 
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP,SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES S 
JOIN CUSTOMERS C ON S.CUSTOMER_ID=C.CUSTOMER_ID 
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,C.MEMBERSHIP;
SELECT * FROM CUSTOMER_REVENUE ORDER BY TOTAL_REVENUE DESC; 

--MATERIALIZED VIEW BRANCH_REVENUE
CREATE OR REPLACE MATERIALIZED VIEW BRANCH_REVENUE AS 
SELECT BRANCH_ID,SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES
GROUP BY BRANCH_ID;
SELECT * FROM BRANCH_REVENUE ORDER BY TOTAL_REVENUE DESC;