--CREATE DATABASE AND SCHEMA
CREATE OR REPLACE DATABASE CUSTOMER_MEMBERSHIP_DW;
USE DATABASE CUSTOMER_MEMBERSHIP_DW;
CREATE OR REPLACE SCHEMA MEMBERSHIP_ANALYTICS;
USE SCHEMA MEMBERSHIP_ANALYTICS;
SELECT CURRENT_DATABASE(),CURRENT_SCHEMA();

--CREATE SCD TYPE 3 DIMENSION
CREATE OR REPLACE TABLE CUSTOMER_MEMBERSHIP_TYPE3(
CUSTOMER_KEY NUMBER AUTOINCREMENT, 
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
CURRENT_MEMBERSHIP VARCHAR(50),
PREVIOUS_MEMBERSHIP VARCHAR(50),
SEGMENT VARCHAR(50)
);

--CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT 
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY=='"'
TRIM_SPACE=TRUE;

--CREATE STAGE 
CREATE OR REPLACE STAGE CUSTOMER_MEMBERSHIP_STAGE FILE_FORMAT=CUSTOMER_CSV_FORMAT;

--COPY INTO TYPE3 TABLE 
COPY INTO CUSTOMER_MEMBERSHIP_TYPE3(
CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,CURRENT_MEMBERSHIP,SEGMENT
) FROM @CUSTOMER_MEMBERSHIP_STAGE/customers_initial.csv 
FILE_FORMAT=CUSTOMER_CSV_FORMAT 
ON_ERROR='ABORT_STATEMENT';
SELECT * FROM CUSTOMER_MEMBERSHIP_TYPE3 ORDER BY CUSTOMER_ID;
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM CUSTOMER_MEMBERSHIP_TYPE3
ORDER BY CUSTOMER_ID;

--APPLY SCD TYPE3 CHANGES: CUSTOMER 101
UPDATE CUSTOMER_MEMBERSHIP_TYPE3 SET PREVIOUS_MEMBERSHIP=CURRENT_MEMBERSHIP,
CURRENT_MEMBERSHIP='Gold',
CITY='Bengaluru',
STATE='Karnataka',
SEGMENT='Premium' WHERE CUSTOMER_ID=101;
--CUSTOMER 103
UPDATE CUSTOMER_MEMBERSHIP_TYPE3 SET PREVIOUS_MEMBERSHIP=CURRENT_MEMBERSHIP,
CURRENT_MEMBERSHIP='Gold',
CITY='Chennai',
STATE='Tamil Nadu',
SEGMENT='Premium' WHERE CUSTOMER_ID=103;
--CUSTOMER 104
UPDATE CUSTOMER_MEMBERSHIP_TYPE3 SET PREVIOUS_MEMBERSHIP=CURRENT_MEMBERSHIP,
CURRENT_MEMBERSHIP='Plantinum' WHERE CUSTOMER_ID=104;
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,CURRENT_MEMBERSHIP,PREVIOUS_MEMBERSHIP,
SEGMENT FROM CUSTOMER_MEMBERSHIP_TYPE3 ORDER BY CUSTOMER_ID;

--DEMONSTRATE SCD TYPE 3
SELECT CUSTOMER_ID,CUSTOMER_NAME,CURRENT_MEMBERSHIP,PREVIOUS_MEMBERSHIP 
FROM CUSTOMER_MEMBERSHIP_TYPE3 WHERE CUSTOMER_ID=101;

--CREATE SCD TYPE 6 DIMENSION
CREATE OR REPLACE TABLE CUSTOMER_MEMBERSHIP_TYPE6(
CUSTOMER_KEY NUMBER AUTOINCREMENT,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
CURRENT_MEMBERSHIP VARCHAR(50),
PREVIOUS_MEMBERSHIP VARCHAR(50),
HISTORICAL_MEMBERSHIP VARCHAR(50),
SEGMENT VARCHAR(50),
EFFECTIVE_DATE DATE,
EXPIRY_DATE DATE,
IS_CURRENT BOOLEAN
);
COPY INTO CUSTOMER_MEMBERSHIP_TYPE6(
CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,CURRENT_MEMBERSHIP,PREVIOUS_MEMBERSHIP,
HISTORICAL_MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,EXPIRY_DATE,IS_CURRENT 
) FROM (
SELECT $1,$2,$3,$4,$5,NULL,$5,$6,'2026-01-01'::DATE,'9999-12-31'::DATE,TRUE 
FROM @CUSTOMER_MEMBERSHIP_STAGE/customers_initial.csv
)
FILE_FORMAT=CUSTOMER_CSV_FORMAT
ON_ERROR='ABORT_STATEMENT';
SELECT * FROM CUSTOMER_MEMBERSHIP_TYPE6 ORDER BY CUSTOMER_ID;

-- CUSTOMER 101 TYPE 6 CHANGE 
UPDATE CUSTOMER_MEMBERSHIP_TYPE6 SET EXPIRY_DATE='2026-03-31'::DATE,IS_CURRENT=FALSE 
WHERE CUSTOMER_ID=101 AND IS_CURRENT=TRUE;
INSERT INTO CUSTOMER_MEMBERSHIP_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    'Bengaluru',
    'Karnataka',
    'Gold',
    CURRENT_MEMBERSHIP,
    'Gold',
    SEGMENT,
    '2026-04-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = FALSE
  AND EXPIRY_DATE = '2026-03-31'::DATE;
  SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

--CUSTOMER 103
UPDATE CUSTOMER_MEMBERSHIP_TYPE6
SET
    EXPIRY_DATE = '2026-04-04'::DATE,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;
INSERT INTO CUSTOMER_MEMBERSHIP_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    'Chennai',
    'Tamil Nadu',
    'Gold',
    CURRENT_MEMBERSHIP,
    'Gold',
    'Premium',
    '2026-04-05'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = FALSE
  AND EXPIRY_DATE = '2026-04-04'::DATE;

--CUSTOMER 104
UPDATE CUSTOMER_MEMBERSHIP_TYPE6
SET
    EXPIRY_DATE = '2026-04-09'::DATE,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;
INSERT INTO CUSTOMER_MEMBERSHIP_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    'Platinum',
    CURRENT_MEMBERSHIP,
    'Platinum',
    SEGMENT,
    '2026-04-10'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = FALSE
  AND EXPIRY_DATE = '2026-04-09'::DATE;
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID IN (103, 104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--DISPLAY COMPLETE TYPE 6 HISTORY
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_MEMBERSHIP_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;
SELECT COUNT(*) AS CURRENT_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE IS_CURRENT = TRUE;
SELECT COUNT(*) AS HISTORICAL_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE IS_CURRENT = FALSE;

--CURRENT CUSTOMER REPORT 
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-- What was Customer 101's membership on March 15, 2026?
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT COUNT(*) AS SCD_TYPE3_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE3;
SELECT COUNT(*) AS SCD_TYPE6_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE6;
SELECT COUNT(*) AS SCD_TYPE6_CURRENT_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE IS_CURRENT = TRUE;
SELECT COUNT(*) AS SCD_TYPE6_HISTORICAL_RECORD_COUNT
FROM CUSTOMER_MEMBERSHIP_TYPE6
WHERE IS_CURRENT = FALSE;