--DATABASE AND SCHEMA
USE DATABASE RETAIL_SALES_DW;
CREATE OR REPLACE SCHEMA RETAIL_SNOWFLAKE;
USE SCHEMA RETAIL_SNOWFLAKE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY='"'
TRIM_SPACE=TRUE 
NULL_IF=('NULL','null','');

--CREATE STAGE
CREATE OR REPLACE STAGE PRJ6_STAGE FILE_FORMAT=CSV_FORMAT;

LIST @PRJ6_STAGE;

--CREATE STAGING TABLES
CREATE OR REPLACE TABLE STG_CUSTOMERS(
CUSTOMER_ID INTEGER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_PRODUCTS(
PRODUCT_ID INTEGER,
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(100),
BRAND VARCHAR(100),
PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE STG_BRANCHES(
BRANCH_ID INTEGER,
BRANCH_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
REGION VARCHAR(50),
MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_CALENDAR(
DATE_ID INTEGER,
DATE_VALUE DATE,
DAY_NUMBER INTEGER,
DAY_NAME VARCHAR(20),
WEEK_NO INTEGER,
MONTH_NAME VARCHAR(20),
QUARTER_NAME VARCHAR(10),
YEAR_NUMBER INTEGER,
IS_WEEKEND VARCHAR(10)
);

CREATE OR REPLACE TABLE STG_SALES(
SALE_ID INTEGER,
CUSTOMER_ID INTEGER,
PRODUCT_ID INTEGER,
BRANCH_ID INTEGER,
DATE_ID INTEGER,
QUANTITY INTEGER,
TOTAL_AMOUNT NUMBER(14,2)
);

--LOAD DATA FROM CSV TO STAGE 
COPY INTO STG_CUSTOMERS FROM @PRJ6_STAGE/customers.csv 
FILE_FORMAT=CSV_FORMAT 
ON_ERROR='ABORT_STATEMENT';

COPY INTO STG_PRODUCTS FROM @PRJ6_STAGE/products.csv 
FILE_FORMAT=CSV_FORMAT 
ON_ERROR='ABORT_STATEMENT';

COPY INTO STG_BRANCHES FROM @PRJ6_STAGE/branches.csv 
FILE_FORMAT=CSV_FORMAT 
ON_ERROR='ABORT_STATEMENT';

COPY INTO STG_CALENDAR FROM @PRJ6_STAGE/calendar.csv 
FILE_FORMAT=CSV_FORMAT
ON_ERROR='ABORT_STATEMENT';

COPY INTO STG_SALES FROM @PRJ6_STAGE/sales.csv 
FILE_FORMAT=CSV_FORMAT
ON_ERROR='ABORT_STATEMENT';

--CREATE DIMENIONS TABLES AND LOAD THE DATA INTO THEM
CREATE OR REPLACE TABLE DIM_REGION(
REGION_KEY INTEGER AUTOINCREMENT,
REGION_NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_DIM_REGION PRIMARY KEY (REGION_KEY)
);
INSERT INTO DIM_REGION (REGION_NAME) 
SELECT DISTINCT REGION FROM STG_BRANCHES ORDER BY REGION;

CREATE OR REPLACE TABLE DIM_STATE(
STATE_KEY INTEGER AUTOINCREMENT,
STATE_NAME VARCHAR(100) NOT NULL,
REGION_KEY INTEGER,
CONSTRAINT PK_DIM_STATE PRIMARY KEY (STATE_KEY),
CONSTRAINT FK_STATE_REGION FOREIGN KEY (REGION_KEY) REFERENCES DIM_REGION(REGION_KEY)
);
INSERT INTO DIM_STATE (
    STATE_NAME,
    REGION_KEY
)
SELECT
    X.STATE_NAME,
    R.REGION_KEY
FROM (
    SELECT 'Andhra Pradesh' AS STATE_NAME, 'South' AS REGION_NAME
    UNION ALL
    SELECT 'Bihar', 'North'
    UNION ALL
    SELECT 'Chandigarh', 'North'
    UNION ALL
    SELECT 'Delhi', 'North'
    UNION ALL
    SELECT 'Gujarat', 'West'
    UNION ALL
    SELECT 'Karnataka', 'South'
    UNION ALL
    SELECT 'Kerala', 'South'
    UNION ALL
    SELECT 'Madhya Pradesh', 'North'
    UNION ALL
    SELECT 'Maharashtra', 'West'
    UNION ALL
    SELECT 'Rajasthan', 'North'
    UNION ALL
    SELECT 'Tamil Nadu', 'South'
    UNION ALL
    SELECT 'Telangana', 'South'
    UNION ALL
    SELECT 'Uttar Pradesh', 'North'
    UNION ALL
    SELECT 'West Bengal', 'East'
) X
JOIN DIM_REGION R
    ON X.REGION_NAME = R.REGION_NAME;
SELECT
    S.STATE_KEY,
    S.STATE_NAME,
    R.REGION_NAME
FROM DIM_STATE S
JOIN DIM_REGION R
    ON S.REGION_KEY = R.REGION_KEY
ORDER BY S.STATE_NAME;

CREATE OR REPLACE TABLE DIM_CITY(
CITY_KEY INTEGER AUTOINCREMENT,
CITY_NAME VARCHAR(100) NOT NULL,
STATE_KEY INTEGER NOT NULL,
CONSTRAINT PK_DIM_CITY PRIMARY KEY (CITY_KEY),
CONSTRAINT FK_CITY_STATE FOREIGN KEY (STATE_KEY) REFERENCES DIM_STATE(STATE_KEY)
);
INSERT INTO DIM_CITY(
CITY_NAME,STATE_KEY 
)
SELECT DISTINCT X.CITY_NAME,S.STATE_KEY FROM (
SELECT CITY AS CITY_NAME,STATE FROM STG_CUSTOMERS 
UNION SELECT CITY AS CITY_NAME,STATE FROM STG_BRANCHES 
) X JOIN DIM_STATE S ON X.STATE=S.STATE_NAME;
SELECT C.CITY_KEY,C.CITY_NAME,S.STATE_NAME FROM DIM_CITY C JOIN DIM_STATE S 
ON C.STATE_KEY=S.STATE_KEY ORDER BY S.STATE_NAME,C.CITY_NAME;

CREATE OR REPLACE TABLE DIM_CATEGORY(
CATEGORY_KEY INTEGER AUTOINCREMENT,
CATEGORY_NAME VARCHAR(100) NOT NULL,
CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (CATEGORY_KEY)
);
INSERT INTO DIM_CATEGORY (
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY
FROM STG_PRODUCTS
ORDER BY CATEGORY;
SELECT * FROM DIM_CATEGORY ORDER BY CATEGORY_KEY;

CREATE OR REPLACE TABLE DIM_BRAND(
BRAND_KEY INTEGER AUTOINCREMENT,
BRAND_NAME VARCHAR(100) NOT NULL,
CATEGORY_KEY INTEGER NOT NULL,
CONSTRAINT PK_DIM_BRAND PRIMARY KEY (BRAND_KEY),
CONSTRAINT FK_BRAND_CATEGORY FOREIGN KEY (CATEGORY_KEY)
REFERENCES DIM_CATEGORY(CATEGORY_KEY)
);
INSERT INTO DIM_BRAND( BRAND_NAME,CATEGORY_KEY)
SELECT DISTINCT P.BRAND,C.CATEGORY_KEY FROM STG_PRODUCTS P 
JOIN DIM_CATEGORY C ON P.CATEGORY=C.CATEGORY_NAME;
SELECT B.BRAND_KEY,B.BRAND_NAME,C.CATEGORY_NAME FROM DIM_BRAND B 
JOIN DIM_CATEGORY C ON B.CATEGORY_KEY=C.CATEGORY_KEY 
ORDER BY C.CATEGORY_NAME,B.BRAND_NAME;

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY INTEGER AUTOINCREMENT,
    PRODUCT_ID INTEGER NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    BRAND_KEY INTEGER NOT NULL,
    PRICE NUMBER(12,2),

    CONSTRAINT PK_DIM_PRODUCT
        PRIMARY KEY (PRODUCT_KEY),

    CONSTRAINT FK_PRODUCT_BRAND
        FOREIGN KEY (BRAND_KEY)
        REFERENCES DIM_BRAND(BRAND_KEY)
);
INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    BRAND_KEY,
    PRICE
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_KEY,
    P.PRICE
FROM STG_PRODUCTS P
JOIN DIM_BRAND B
    ON P.BRAND = B.BRAND_NAME
JOIN DIM_CATEGORY C
    ON B.CATEGORY_KEY = C.CATEGORY_KEY
   AND P.CATEGORY = C.CATEGORY_NAME;
SELECT C.CATEGORY_NAME,B.BRAND_NAME,P.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE 
FROM DIM_PRODUCT P JOIN DIM_BRAND B ON P.BRAND_KEY=B.BRAND_KEY 
JOIN DIM_CATEGORY C ON B.CATEGORY_KEY=C.CATEGORY_KEY 
ORDER BY C.CATEGORY_NAME,B.BRAND_NAME,P.PRODUCT_NAME;

CREATE OR REPLACE TABLE DIM_BRANCH(
BRANCH_KEY INTEGER AUTOINCREMENT,
BRANCH_ID INTEGER NOT NULL,
BRANCH_NAME VARCHAR(100) NOT NULL,
CITY_KEY INTEGER NOT NULL,
MANAGER_NAME VARCHAR(100),
CONSTRAINT PK_DIM_BRANCH PRIMARY KEY (BRANCH_KEY),
CONSTRAINT FK_BRANCH_CITY FOREIGN KEY (CITY_KEY) REFERENCES DIM_CITY(CITY_KEY)
);
INSERT INTO DIM_BRANCH( BRANCH_ID,BRANCH_NAME,CITY_KEY,MANAGER_NAME)
SELECT B.BRANCH_ID,B.BRANCH_NAME,C.CITY_KEY,B.MANAGER_NAME FROM STG_BRANCHES B 
JOIN DIM_CITY C ON B.CITY=C.CITY_NAME JOIN DIM_STATE S ON C.STATE_KEY=S.STATE_KEY 
AND B.STATE=S.STATE_NAME;
SELECT R.REGION_NAME,S.STATE_NAME,C.CITY_NAME,B.BRANCH_ID,B.BRANCH_NAME,B.MANAGER_NAME 
FROM DIM_BRANCH B JOIN DIM_CITY C ON B.CITY_KEY=C.CITY_KEY JOIN DIM_STATE S 
ON C.STATE_KEY=S.STATE_KEY JOIN DIM_REGION R ON S.REGION_KEY=R.REGION_KEY 
ORDER BY R.REGION_NAME,S.STATE_NAME,C.CITY_NAME;

CREATE OR REPLACE TABLE DIM_CUSTOMER(
CUSTOMER_KEY INTEGER AUTOINCREMENT,
CUSTOMER_ID INTEGER NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CITY_KEY INTEGER NOT NULL,
MEMBERSHIP VARCHAR(50),
CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY),
CONSTRAINT FK_CUSTOMER_CITY FOREIGN KEY (CITY_KEY) REFERENCES DIM_CITY(CITY_KEY)
);
--LOAD CUSTOMERS
INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY_KEY,
    MEMBERSHIP
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_KEY,
    C.MEMBERSHIP
FROM STG_CUSTOMERS C
JOIN DIM_CITY CI
    ON C.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON CI.STATE_KEY = S.STATE_KEY
   AND C.STATE = S.STATE_NAME;
   SELECT
    S.STATE_NAME,
    C.CITY_NAME,
    CU.CUSTOMER_ID,
    CU.CUSTOMER_NAME,
    CU.MEMBERSHIP
FROM DIM_CUSTOMER CU
JOIN DIM_CITY C
    ON CU.CITY_KEY = C.CITY_KEY
JOIN DIM_STATE S
    ON C.STATE_KEY = S.STATE_KEY
ORDER BY
    S.STATE_NAME,
    C.CITY_NAME,
    CU.CUSTOMER_NAME;
SELECT
    S.STATE_NAME,
    COUNT(DISTINCT C.CITY_KEY) AS CITY_COUNT,
    COUNT(DISTINCT CU.CUSTOMER_KEY) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER CU
JOIN DIM_CITY C
    ON CU.CITY_KEY = C.CITY_KEY
JOIN DIM_STATE S
    ON C.STATE_KEY = S.STATE_KEY
GROUP BY S.STATE_NAME
ORDER BY S.STATE_NAME;

CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_KEY INTEGER AUTOINCREMENT,
    YEAR_NUMBER INTEGER NOT NULL,

    CONSTRAINT PK_DIM_YEAR
        PRIMARY KEY (YEAR_KEY)
);
INSERT INTO DIM_YEAR (
    YEAR_NUMBER
)
SELECT DISTINCT
    YEAR_NUMBER
FROM STG_CALENDAR
ORDER BY YEAR_NUMBER;

CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_KEY INTEGER AUTOINCREMENT,
    QUARTER_NAME VARCHAR(10) NOT NULL,
    YEAR_KEY INTEGER NOT NULL,

    CONSTRAINT PK_DIM_QUARTER
        PRIMARY KEY (QUARTER_KEY),

    CONSTRAINT FK_QUARTER_YEAR
        FOREIGN KEY (YEAR_KEY)
        REFERENCES DIM_YEAR(YEAR_KEY)
);
INSERT INTO DIM_QUARTER (
    QUARTER_NAME,
    YEAR_KEY
)
SELECT DISTINCT
    C.QUARTER_NAME,
    Y.YEAR_KEY
FROM STG_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR_NUMBER = Y.YEAR_NUMBER;

CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_KEY INTEGER AUTOINCREMENT,
    MONTH_NAME VARCHAR(20) NOT NULL,
    QUARTER_KEY INTEGER NOT NULL,

    CONSTRAINT PK_DIM_MONTH
        PRIMARY KEY (MONTH_KEY),

    CONSTRAINT FK_MONTH_QUARTER
        FOREIGN KEY (QUARTER_KEY)
        REFERENCES DIM_QUARTER(QUARTER_KEY)
);
INSERT INTO DIM_MONTH (
    MONTH_NAME,
    QUARTER_KEY
)
SELECT DISTINCT
    C.MONTH_NAME,
    Q.QUARTER_KEY
FROM STG_CALENDAR C
JOIN DIM_QUARTER Q
    ON C.QUARTER_NAME = Q.QUARTER_NAME
JOIN DIM_YEAR Y
    ON C.YEAR_NUMBER = Y.YEAR_NUMBER
   AND Q.YEAR_KEY = Y.YEAR_KEY;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INTEGER AUTOINCREMENT,
    DATE_ID INTEGER NOT NULL,
    DATE_VALUE DATE NOT NULL,
    DAY_NUMBER INTEGER,
    DAY_NAME VARCHAR(20),
    WEEK_NO INTEGER,
    MONTH_KEY INTEGER NOT NULL,
    IS_WEEKEND VARCHAR(10),

    CONSTRAINT PK_DIM_DATE
        PRIMARY KEY (DATE_KEY),

    CONSTRAINT FK_DATE_MONTH
        FOREIGN KEY (MONTH_KEY)
        REFERENCES DIM_MONTH(MONTH_KEY)
);
INSERT INTO DIM_DATE (
    DATE_ID,
    DATE_VALUE,
    DAY_NUMBER,
    DAY_NAME,
    WEEK_NO,
    MONTH_KEY,
    IS_WEEKEND
)
SELECT
    C.DATE_ID,
    C.DATE_VALUE,
    C.DAY_NUMBER,
    C.DAY_NAME,
    C.WEEK_NO,
    M.MONTH_KEY,
    C.IS_WEEKEND
FROM STG_CALENDAR C
JOIN DIM_MONTH M
    ON C.MONTH_NAME = M.MONTH_NAME
JOIN DIM_QUARTER Q
    ON M.QUARTER_KEY = Q.QUARTER_KEY
   AND C.QUARTER_NAME = Q.QUARTER_NAME
JOIN DIM_YEAR Y
    ON Q.YEAR_KEY = Y.YEAR_KEY
   AND C.YEAR_NUMBER = Y.YEAR_NUMBER;

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_KEY INTEGER AUTOINCREMENT,
    SALE_ID INTEGER NOT NULL,
    CUSTOMER_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    BRANCH_KEY INTEGER NOT NULL,
    DATE_KEY INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    TOTAL_AMOUNT NUMBER(14,2) NOT NULL,

    CONSTRAINT PK_FACT_SALES
        PRIMARY KEY (SALE_KEY),

    CONSTRAINT FK_FACT_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),

    CONSTRAINT FK_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY),

    CONSTRAINT FK_FACT_BRANCH
        FOREIGN KEY (BRANCH_KEY)
        REFERENCES DIM_BRANCH(BRANCH_KEY),

    CONSTRAINT FK_FACT_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);
INSERT INTO FACT_SALES (
    SALE_ID,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    BRANCH_KEY,
    DATE_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    S.SALE_ID,
    C.CUSTOMER_KEY,
    P.PRODUCT_KEY,
    B.BRANCH_KEY,
    D.DATE_KEY,
    S.QUANTITY,
    S.TOTAL_AMOUNT
FROM STG_SALES S
JOIN DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON S.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON S.DATE_ID = D.DATE_ID;

SELECT
    COUNT(*) AS TOTAL_FACT_ROWS,
    COUNT(C.CUSTOMER_KEY) AS VALID_CUSTOMERS,
    COUNT(P.PRODUCT_KEY) AS VALID_PRODUCTS,
    COUNT(B.BRANCH_KEY) AS VALID_BRANCHES,
    COUNT(D.DATE_KEY) AS VALID_DATES
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_KEY = B.BRANCH_KEY
LEFT JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY;

--CUSTOMER-WISE SALES
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;

--PRODUCT-WISE REVENUE
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

--BRAND-WISE REVENUE
SELECT
    B.BRAND_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
JOIN DIM_BRAND B
    ON P.BRAND_KEY = B.BRAND_KEY
GROUP BY B.BRAND_NAME
ORDER BY TOTAL_REVENUE DESC;

--CATEGORY-WISE REVENUE
SELECT
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
JOIN DIM_BRAND B
    ON P.BRAND_KEY = B.BRAND_KEY
JOIN DIM_CATEGORY C
    ON B.CATEGORY_KEY = C.CATEGORY_KEY
GROUP BY C.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

--CITY-WISE SALES
SELECT
    C.CITY_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_KEY = B.BRANCH_KEY
JOIN DIM_CITY C
    ON B.CITY_KEY = C.CITY_KEY
GROUP BY C.CITY_NAME
ORDER BY TOTAL_SALES DESC;

--STATE-WISE REVENUE
SELECT
    S.STATE_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_KEY = B.BRANCH_KEY
JOIN DIM_CITY C
    ON B.CITY_KEY = C.CITY_KEY
JOIN DIM_STATE S
    ON C.STATE_KEY = S.STATE_KEY
GROUP BY S.STATE_NAME
ORDER BY TOTAL_REVENUE DESC;

--REGION-WISE REVENUE
SELECT
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_KEY = B.BRANCH_KEY
JOIN DIM_CITY C
    ON B.CITY_KEY = C.CITY_KEY
JOIN DIM_STATE S
    ON C.STATE_KEY = S.STATE_KEY
JOIN DIM_REGION R
    ON S.REGION_KEY = R.REGION_KEY
GROUP BY R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

--MONTHLY REVENUE 
SELECT
    M.MONTH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
JOIN DIM_MONTH M
    ON D.MONTH_KEY = M.MONTH_KEY
GROUP BY M.MONTH_NAME
ORDER BY TOTAL_REVENUE DESC;

--QUARTERLY REVENUE
SELECT
    Q.QUARTER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
JOIN DIM_MONTH M
    ON D.MONTH_KEY = M.MONTH_KEY
JOIN DIM_QUARTER Q
    ON M.QUARTER_KEY = Q.QUARTER_KEY
GROUP BY Q.QUARTER_NAME
ORDER BY TOTAL_REVENUE DESC;

--TOP 10 CUSTOMERS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--TOP 10 PRODUCTS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--TOP 10 BRANCHES
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_KEY = B.BRANCH_KEY
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--CUSTOMER PURCHASE TREND
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    D.DATE_VALUE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_PURCHASE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    D.DATE_VALUE
ORDER BY
    C.CUSTOMER_ID,
    D.DATE_VALUE;

--PRODUCT PERFORMANCE DASHBOARD
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(
        SUM(F.TOTAL_AMOUNT) / NULLIF(SUM(F.QUANTITY), 0),
        2
    ) AS AVG_SELLING_VALUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
JOIN DIM_BRAND B
    ON P.BRAND_KEY = B.BRAND_KEY
JOIN DIM_CATEGORY C
    ON B.CATEGORY_KEY = C.CATEGORY_KEY
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

--REGIONAL SALES DASHBOARD
SELECT
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_KEY = BR.BRANCH_KEY
JOIN DIM_CITY C
    ON BR.CITY_KEY = C.CITY_KEY
JOIN DIM_STATE S
    ON C.STATE_KEY = S.STATE_KEY
JOIN DIM_REGION R
    ON S.REGION_KEY = R.REGION_KEY
GROUP BY
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME
ORDER BY
    R.REGION_NAME,
    TOTAL_REVENUE DESC;

--FINAL SCHEMA VALIDATION 
SELECT 'DIM_REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_REGION
UNION ALL
SELECT 'DIM_STATE', COUNT(*) FROM DIM_STATE
UNION ALL
SELECT 'DIM_CITY', COUNT(*) FROM DIM_CITY
UNION ALL
SELECT 'DIM_CATEGORY', COUNT(*) FROM DIM_CATEGORY
UNION ALL
SELECT 'DIM_BRAND', COUNT(*) FROM DIM_BRAND
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'DIM_BRANCH', COUNT(*) FROM DIM_BRANCH
UNION ALL
SELECT 'DIM_YEAR', COUNT(*) FROM DIM_YEAR
UNION ALL
SELECT 'DIM_QUARTER', COUNT(*) FROM DIM_QUARTER
UNION ALL
SELECT 'DIM_MONTH', COUNT(*) FROM DIM_MONTH
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE
UNION ALL
SELECT 'DIM_CUSTOMER', COUNT(*) FROM DIM_CUSTOMER
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM FACT_SALES;

SELECT
    COUNT(*) AS TOTAL_TRANSACTIONS,
    COUNT(DISTINCT SALE_ID) AS UNIQUE_SALES,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES;