USE DATABASE PROJECT_14A_DB;
USE SCHEMA ECOMMERCE_ANALYTICS;

--CREATE BRONZE TABLE
CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    RAW_PAYLOAD VARIANT
);

--STAGING
CREATE OR REPLACE FILE FORMAT PAYMENT_JSON_FORMAT
TYPE = 'JSON';
CREATE OR REPLACE STAGE PAYMENT_BRONZE_STAGE
FILE_FORMAT = PAYMENT_JSON_FORMAT;
LIST @PAYMENT_BRONZE_STAGE;
COPY INTO BRONZE_PAYMENT_PAYLOADS
FROM @PAYMENT_BRONZE_STAGE;

CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR,
    TXN_TIME TIMESTAMP_TZ,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR,
    MASKED_CARD VARCHAR,
    GROSS_AMOUNT NUMBER(18,2),
    FEE_PCT NUMBER(5,2),
    PROCESSING_FEE NUMBER(18,2),
    NET_SETTLEMENT_AMOUNT NUMBER(18,2),
    STATUS VARCHAR
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR AS TXN_ID,

    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ AS TXN_TIME,

    RAW_PAYLOAD:merchant_id::NUMBER AS MERCHANT_ID,

    RAW_PAYLOAD:merchant_name::VARCHAR AS MERCHANT_NAME,

    'XXXX-XXXX-XXXX-' ||
        RIGHT(RAW_PAYLOAD:card_number::VARCHAR, 4) AS MASKED_CARD,

    RAW_PAYLOAD:amount::NUMBER(18,2) AS GROSS_AMOUNT,

    RAW_PAYLOAD:fee_pct::NUMBER(5,2) AS FEE_PCT,

    ROUND(
        RAW_PAYLOAD:amount::NUMBER(18,2)
        * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100),
        2
    ) AS PROCESSING_FEE,

    ROUND(
        RAW_PAYLOAD:amount::NUMBER(18,2)
        -
        (
            RAW_PAYLOAD:amount::NUMBER(18,2)
            * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100)
        ),
        2
    ) AS NET_SETTLEMENT_AMOUNT,

    RAW_PAYLOAD:status::VARCHAR AS STATUS

FROM BRONZE_PAYMENT_PAYLOADS;
SELECT *
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR,
    TOTAL_APPROVED_GROSS NUMBER(18,2),
    TOTAL_GATEWAY_FEES NUMBER(18,2),
    TOTAL_NET_PAYOUT NUMBER(18,2),
    APPROVED_COUNT NUMBER
);
INSERT INTO GOLD_MERCHANT_SETTLEMENTS
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT) AS TOTAL_APPROVED_GROSS,
    SUM(PROCESSING_FEE) AS TOTAL_GATEWAY_FEES,
    SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,
    COUNT(*) AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY
    MERCHANT_ID,
    MERCHANT_NAME
ORDER BY MERCHANT_ID;
SELECT *
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

SELECT CURRENT_TIMESTAMP();
SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;
UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';
SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;
SELECT
    QUERY_ID,
    QUERY_TEXT,
    START_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION())
WHERE QUERY_TEXT ILIKE 'UPDATE SILVER_CLEANED_TRANSACTIONS%'
ORDER BY START_TIME DESC
LIMIT 1;
MERGE INTO SILVER_CLEANED_TRANSACTIONS AS CURRENT_DATA
USING (
    SELECT
        TXN_ID,
        STATUS
    FROM SILVER_CLEANED_TRANSACTIONS
    BEFORE (STATEMENT => '01c755a8-3203-6e51-0018-46ee000d931e')
    WHERE MERCHANT_NAME = 'TechZone'
) AS HISTORICAL_DATA
ON CURRENT_DATA.TXN_ID = HISTORICAL_DATA.TXN_ID

WHEN MATCHED THEN
    UPDATE SET CURRENT_DATA.STATUS = HISTORICAL_DATA.STATUS;
SELECT
    MERCHANT_NAME,
    SUM(CASE WHEN STATUS = 'APPROVED' THEN 1 ELSE 0 END) AS APPROVED_COUNT,
    SUM(CASE WHEN STATUS = 'REFUNDED' THEN 1 ELSE 0 END) AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;
WITH BRONZE_TOTAL AS (
    SELECT
        SUM(RAW_PAYLOAD:amount::NUMBER(18,2)) AS BRONZE_GROSS_SUM
    FROM BRONZE_PAYMENT_PAYLOADS
),

SILVER_TOTAL AS (
    SELECT
        SUM(GROSS_AMOUNT) AS SILVER_GROSS_SUM
    FROM SILVER_CLEANED_TRANSACTIONS
),

GOLD_TOTAL AS (
    SELECT
        SUM(TOTAL_APPROVED_GROSS) AS GOLD_GROSS_SUM
    FROM GOLD_MERCHANT_SETTLEMENTS
)

SELECT
    B.BRONZE_GROSS_SUM,
    S.SILVER_GROSS_SUM,
    G.GOLD_GROSS_SUM,
    
    CASE
        WHEN B.BRONZE_GROSS_SUM = S.SILVER_GROSS_SUM
         AND G.GOLD_GROSS_SUM = (
             SELECT SUM(GROSS_AMOUNT)
             FROM SILVER_CLEANED_TRANSACTIONS
             WHERE STATUS = 'APPROVED'
         )
        THEN TRUE
        ELSE FALSE
    END AS DATA_MATCH_FLAG

FROM BRONZE_TOTAL B
CROSS JOIN SILVER_TOTAL S
CROSS JOIN GOLD_TOTAL G;