-- CREATE DATABASE AND SCHEMA 
CREATE DATABASE IF NOT EXISTS LOGISTICS_LAKEHOUSE_DB;
USE DATABASE LOGISTICS_LAKEHOUSE_DB;
CREATE SCHEMA IF NOT EXISTS FLEET_CORE;
USE SCHEMA FLEET_CORE;

-- CAREATE BRONZE TABLE
CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS(
INGEST_ID NUMBER AUTOINCREMENT,
RAW_PAYLOAD VARIANT,
RECORDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREATE STAGING
CREATE OR REPLACE STAGE VIVA_STAGING;
LIST @VIVA_STAGING;

-- COPY INTO 
COPY INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) FROM @VIVA_STAGING 
FILE_FORMAT=(
TYPE='JSON'
)
ON_ERROR='CONTINUE';

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_IOT_STREAMS;

SELECT RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,
RAW_PAYLOAD:payload_type::STRING AS PAYLOAD_TYPE,
RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TIMESTAMP,
RAW_PAYLOAD:data:vehicle_id::STRING AS VEHICLE_ID,
RAW_PAYLOAD:data:shipment_id::STRING AS SHIPMENT_ID,
RAW_PAYLOAD:data:declared_value::NUMBER(18,2) AS DECLARED_VALUE 
FROM BRONZE_IOT_STREAMS ORDER BY INGEST_ID;

CREATE OR REPLACE TABLE QUARANTIE_IOT_PAYLOADS(
QUARANTINE_ID NUMBER AUTOINCREMENT,
RAW_RECORD_TEXT STRING,
REASON STRING 
);
INSERT INTO QUARANTIE_IOT_PAYLOADS(
RAW_RECORD_TEXT,REASON
)
SELECT 'MALFORMED_IOT_SENSOR_BINARY_BURST_DATA_ERR','MALFORMED_JSON_BODY'
WHERE TRY_PARSE_JSON(
'MALFORMED_IOT_SENSOR_BINARY_BURST_DATA_ERR'
) IS NULL;
SELECT * FROM QUARANTIE_IOT_PAYLOADS;

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE(
SHIPMENT_ID STRING,
PAYLOAD_ID STRING,
VEHICLE_ID STRING,
DESTINATION_COUNTRY STRING,
DECLARED_VALUE NUMBER(18,2),
DUTY_PCT NUMBER(5,2),
DUTY_AMOUNT_DUE NUMBER(18,2),
BORDER_CODE STRING,
CLEARANCE_STATUS STRING 
);

INSERT INTO SILVER_CUSTOMS_CLEARANCE
(
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
)
SELECT
    RAW_PAYLOAD:data:shipment_id::STRING AS SHIPMENT_ID,
    RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,
    RAW_PAYLOAD:data:vehicle_id::STRING AS VEHICLE_ID,
    RAW_PAYLOAD:data:destination_country::STRING AS DESTINATION_COUNTRY,
    RAW_PAYLOAD:data:declared_value::NUMBER(18,2) AS DECLARED_VALUE,
    RAW_PAYLOAD:data:duty_pct::NUMBER(5,2) AS DUTY_PCT,

    (
        RAW_PAYLOAD:data:declared_value::NUMBER(18,2)
        *
        RAW_PAYLOAD:data:duty_pct::NUMBER(5,2)
        / 100
    )::NUMBER(18,2) AS DUTY_AMOUNT_DUE,

    RAW_PAYLOAD:data:border_clearance_code::STRING AS BORDER_CODE,

    RAW_PAYLOAD:data:clearance_status::STRING AS CLEARANCE_STATUS

FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS';

CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY(
DEST_COUNTRY STRING,
TOTAL_CLEARED_VAL NUMBER(18,2),
TOTAL_DUTIES_COLLECTED NUMBER(18,2),
AVG_DUTY_RATE_PCT NUMBER(10,2),
CLEARED_SHIPMENTS NUMBER
);
INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
(
    DEST_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS
)
SELECT
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    SUM(DECLARED_VALUE) AS TOTAL_CLEARED_VAL,
    SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTIES_COLLECTED,
    ROUND(AVG(DUTY_PCT), 2) AS AVG_DUTY_RATE_PCT,
    COUNT(*) AS CLEARED_SHIPMENTS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;

-- DISASTER RECOVERY VIA SNOWFLAKE TIME TRAVEL
SELECT SHIPMENT_ID,DESTINATION_COUNTRY,CLEARANCE_STATUS 
FROM SILVER_CUSTOMS_CLEARANCE ORDER BY SHIPMENT_ID;

UPDATE SILVER_CUSTOMS_CLEARANCE SET CLEARANCE_STATUS='REJECTED'
WHERE DESTINATION_COUNTRY='CAN';

SELECT SHIPMENT_ID,DESTINATION_COUNTRY,CLEARANCE_STATUS 
FROM SILVER_CUSTOMS_CLEARANCE ORDER BY SHIPMENT_ID;

SELECT QUERY_ID,QUERY_TEXT,START_TIME,END_TIME 
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY()) 
WHERE QUERY_TEXT ILIKE '%UPDATE SILVER_CUSTOMS_CLEARANCE%'
ORDER BY START_TIME DESC LIMIT 5;

SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (
    STATEMENT => '01c76573-3203-7613-0018-46ee00101266'
)
ORDER BY SHIPMENT_ID;

--CREATE RECOVERY COPY
CREATE OR REPLACE TEMPORARY TABLE SILVER_RECOVERY AS
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (
    STATEMENT => '01c76573-3203-7613-0018-46ee00101266'
);
SELECT *
FROM SILVER_RECOVERY
ORDER BY SHIPMENT_ID;

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE AS
SELECT *
FROM SILVER_RECOVERY;
SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

SELECT
    DESTINATION_COUNTRY,

    SUM(
        CASE
            WHEN CLEARANCE_STATUS = 'CLEARED'
            THEN 1
            ELSE 0
        END
    ) AS CLEARED_COUNT,

    SUM(
        CASE
            WHEN CLEARANCE_STATUS = 'REJECTED'
            THEN 1
            ELSE 0
        END
    ) AS REJECTED_COUNT

FROM SILVER_CUSTOMS_CLEARANCE

GROUP BY DESTINATION_COUNTRY

ORDER BY DESTINATION_COUNTRY;

WITH BRONZE_TOTAL AS (
    SELECT
        SUM(
            RAW_PAYLOAD:data:declared_value::NUMBER(18,2)
        ) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_IOT_STREAMS
    WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS'
),

SILVER_TOTAL AS (
    SELECT
        SUM(DECLARED_VALUE) AS SILVER_GROSS_TOTAL
    FROM SILVER_CUSTOMS_CLEARANCE
),

GOLD_TOTAL AS (
    SELECT
        SUM(TOTAL_CLEARED_VAL) AS GOLD_GROSS_TOTAL
    FROM GOLD_COUNTRY_DUTY_SUMMARY
)

SELECT
    B.BRONZE_GROSS_TOTAL,
    S.SILVER_GROSS_TOTAL,
    G.GOLD_GROSS_TOTAL,

    CASE
        WHEN B.BRONZE_GROSS_TOTAL = S.SILVER_GROSS_TOTAL
         AND G.GOLD_GROSS_TOTAL <= S.SILVER_GROSS_TOTAL
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG

FROM BRONZE_TOTAL B
CROSS JOIN SILVER_TOTAL S
CROSS JOIN GOLD_TOTAL G;