-- CREATE DATABSE AND SCHEMA
CREATE OR REPLACE DATABASE CUSTOMER_HISTORY_DB;
USE DATABASE CUSTOMER_HISTORY_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_SCD;
USE SCHEMA CUSTOMER_SCD;

--CREATE TABLE
CREATE OR REPLACE TABLE CUSTOMER_SCD_TYPE1(
CUSTOMER_KEY NUMBER,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
MEMBERSHIP VARCHAR(30),
SEGMENT VARCHAR(30)
);

--CREATE CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY='"';
--CREATE STAGE
CREATE OR REPLACE STAGE CUSTOMER_STAGE 
FILE_FORMAT=CUSTOMER_CSV_FORMAT;

CREATE OR REPLACE TABLE CUSTOMER_INITIAL_RAW (
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
MEMBERSHIP VARCHAR(30),
SEGMENT VARCHAR(30)
);
COPY INTO CUSTOMER_INITIAL_RAW FROM @CUSTOMER_STAGE 
FILE_FORMAT=(
FORMAT_NAME='CUSTOMER_CSV_FORMAT'
);
INSERT INTO CUSTOMER_SCD_TYPE1(
CUSTOMER_KEY,
CUSTOMER_ID,
CUSTOMER_NAME,
CITY,
STATE,
MEMBERSHIP,
SEGMENT
)
SELECT ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_KEY,CUSTOMER_ID,
CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT FROM CUSTOMER_INITIAL_RAW;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES_RAW(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
MEMBERSHIP VARCHAR(30),
SEGMENT VARCHAR(30),
EFFECTIVE_DATE DATE 
);
COPY INTO CUSTOMER_UPDATES_RAW FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT=(
FORMAT_NAME='CUSTOMER_CSV_FORMAT'
)
ON_ERROR='ABORT_STATEMENT';

--APPLY SCD TYPE 1 UPDATE 
UPDATE CUSTOMER_SCD_TYPE1 AS T SET CUSTOMER_NAME=S.CUSTOMER_NAME,
CITY=S.CITY,
STATE=S.STATE,
MEMBERSHIP=S.MEMBERSHIP,
SEGMENT=S.SEGMENT FROM CUSTOMER_UPDATES_RAW AS S WHERE T.CUSTOMER_ID=S.CUSTOMER_ID;

SELECT * FROM CUSTOMER_SCD_TYPE1 ORDER BY CUSTOMER_ID;

--DEMONSTRATE TYPE 1 HISTORY LOSS 
SELECT CUSTOMER_ID,CITY,STATE,MEMBERSHIP FROM CUSTOMER_SCD_TYPE1 
WHERE CUSTOMER_ID=101;
SELECT COUNT(*) AS TYPE1_RECORD_COUNT FROM CUSTOMER_SCD_TYPE1;

CREATE OR REPLACE TABLE CUSTOMER_SCD_TYPE2(
CUSTOMER_KEY NUMBER AUTOINCREMENT,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
SEGMENT VARCHAR(30),
MEMBERSHIP VARCHAR(30),
EFFECTIVE_DATE DATE,
EXPIRY_DATE DATE,
IS_CURRENT BOOLEAN
);
DESC TABLE CUSTOMER_SCD_TYPE2;

list @CUSTOMER_STAGE;
SELECT COUNT(*) AS ROW_COUNT FROM CUSTOMER_INITIAL_RAW;
INSERT INTO CUSTOMER_SCD_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    R.CUSTOMER_ID,
    R.CUSTOMER_NAME,
    R.CITY,
    R.STATE,
    R.MEMBERSHIP,
    R.SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_INITIAL_RAW AS R;
SELECT COUNT(*) AS TOTAL_RECORDS,COUNT_IF(IS_CURRENT=TRUE) AS CURRENT_RECORDS 
FROM CUSTOMER_SCD_TYPE2;

--APPLY TYPE 2 CHANGES 
UPDATE CUSTOMER_SCD_TYPE2 SET EXPIRY_DATE='2026-03-31'::DATE,IS_CURRENT=FALSE
WHERE CUSTOMER_ID=101 AND IS_CURRENT=TRUE;
SELECT * FROM CUSTOMER_SCD_TYPE2 WHERE CUSTOMER_ID=101;

--INSERT CUSTOMER 101'S NEW VERSION
INSERT INTO CUSTOMER_SCD_TYPE2(
CUSTOMER_ID,
CUSTOMER_NAME,
CITY,
STATE,
MEMBERSHIP,
SEGMENT,
EFFECTIVE_DATE,
EXPIRY_DATE,
IS_CURRENT
)
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,
'9999-12-31'::DATE,TRUE FROM CUSTOMER_UPDATES_RAW WHERE CUSTOMER_ID=101;
SELECT CUSTOMER_KEY,CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,EFFECTIVE_DATE,
EXPIRY_DATE,IS_CURRENT FROM CUSTOMER_SCD_TYPE2 WHERE CUSTOMER_ID=101 
ORDER BY EFFECTIVE_DATE;

--CUSTOMER 103 TYPE 2 CHANGE
UPDATE CUSTOMER_SCD_TYPE2 SET EXPIRY_DATE='2026-04-04'::DATE,IS_CURRENT=FALSE 
WHERE CUSTOMER_ID=103 AND IS_CURRENT=TRUE;
INSERT INTO CUSTOMER_SCD_TYPE2 (
CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,EXPIRY_DATE,
IS_CURRENT
)
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,
'9999-12-31'::DATE,TRUE FROM CUSTOMER_UPDATES_RAW WHERE CUSTOMER_ID=103;
SELECT CUSTOMER_KEY,CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,EFFECTIVE_DATE,
EXPIRY_DATE,IS_CURRENT FROM CUSTOMER_SCD_TYPE2 WHERE CUSTOMER_ID=103 
ORDER BY EFFECTIVE_DATE;

--CUSTOMER 104 TYPE 2 CHANGE
UPDATE CUSTOMER_SCD_TYPE2 SET EXPIRY_DATE='2026-04-09'::DATE,IS_CURRENT=FALSE 
WHERE CUSTOMER_ID=104 AND IS_CURRENT=TRUE;
INSERT INTO CUSTOMER_SCD_TYPE2(
CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,EXPIRY_DATE,
IS_CURRENT
)
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT,EFFECTIVE_DATE,
'9999-12-31'::DATE,TRUE FROM CUSTOMER_UPDATES_RAW WHERE CUSTOMER_ID=104;
SELECT CUSTOMER_KEY,CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,EFFECTIVE_DATE,
EXPIRY_DATE,IS_CURRENT FROM CUSTOMER_SCD_TYPE2 WHERE CUSTOMER_ID=104 
ORDER BY EFFECTIVE_DATE;

--DISPLAY COMPLETE TYPE 2 HISTORY
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,EFFECTIVE_DATE,EXPIRY_DATE,
IS_CURRENT FROM CUSTOMER_SCD_TYPE2 ORDER BY CUSTOMER_ID,EFFECTIVE_DATE;
SELECT COUNT(*) AS TOTAL_RECORDS,COUNT_IF(IS_CURRENT=TRUE) AS CURRENT_RECORDS,
COUNT_IF(IS_CURRENT=FALSE) AS HISTORICAL_RECORDS FROM CUSTOMER_SCD_TYPE2;

--DISPLAY CURRENT CUSTOMER RECORDS
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT 
FROM CUSTOMER_SCD_TYPE2 WHERE IS_CURRENT=TRUE ORDER BY CUSTOMER_ID;

--HISTORICAL CUSTOMER ANALYSIS 
SELECT CUSTOMER_ID,CUSTOMER_NAME,MEMBERSHIP,CITY,EFFECTIVE_DATE,EXPIRY_DATE 
FROM CUSTOMER_SCD_TYPE2 WHERE CUSTOMER_ID=101 AND '2026-03-15'::DATE BETWEEN 
EFFECTIVE_DATE AND EXPIRY_DATE;

--COMPARE SCD TYPE 1 VS 2 
SELECT 'Old value preserved?' AS FEATURE,
'No' AS TYPE_1,
'Yes' AS TYPE_2 
UNION ALL 
SELECT 'New row created?','No','Yes'
UNION ALL 
SELECT 'Historical analysis','No','Yes'
UNION ALL 
SELECT 'Effective Date','No','Yes'
UNION ALL 
SELECT 'Expiry Date','No','Yes'
UNION ALL 
SELECT 'IS_CURRENT','No','Yes'
UNION ALL 
SELECT 'Storage Required','Lower','Higher';

--FINAL VALIDATION 
SELECT(
SELECT COUNT(*) FROM CUSTOMER_SCD_TYPE1
) AS TYPE1_RECORDS,
(SELECT COUNT(*) FROM CUSTOMER_SCD_TYPE2) AS TYPE2_RECORDS,
(SELECT COUNT(*) FROM CUSTOMER_SCD_TYPE2 WHERE IS_CURRENT=TRUE) AS TYPE2_CURRENT_RECORDS,
(SELECT COUNT(*) FROM CUSTOMER_SCD_TYPE2 WHERE IS_CURRENT=FALSE) AS 
TYPE2_HISTORICAL_RECORDS;