CREATE OR REPLACE DATABASE RETAIL_SALES_DW;
USE DATABASE RETAIL_SALES_DW;
CREATE OR REPLACE SCHEMA RETAIL_ANALYTICS;
USE SCHEMA RETAIL_ANALYTICS;

--CREATE STAGE CUSTOMER TABLE
CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

--PRODUCTS
CREATE OR REPLACE TABLE STG_PRODUCTS(
PRODUCT_ID INTEGER,
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(100),
BRAND VARCHAR(100),
PRICE NUMBER(12,2)
);

--BRANCHES
CREATE OR REPLACE TABLE STG_BRANCHES(
BRANCH_ID INTEGER,
BRANCH_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
REGION VARCHAR(50),
MANAGER_NAME VARCHAR(100)
);

--CALENDAR
CREATE OR REPLACE TABLE STG_CALENDAR(
DATE_ID INTEGER,
DATE DATE,
DAY INTEGER,
DAY_NAME VARCHAR(20),
WEEK_NO INTEGER,
MONTH VARCHAR(20),
QUARTER VARCHAR(10),
YEAR INTEGER,
IS_WEEKEND VARCHAR(5)
);

--SALES
CREATE OR REPLACE TABLE STG_SALES(
SALE_ID INTEGER,
CUSTOMER_ID INTEGER,
PRODUCT_ID INTEGER,
BRANCH_ID INTEGER,
DATE_ID INTEGER,
QUANTITY INTEGER,
TOTAL_AMOUNT NUMBER(14,2)
);

CREATE OR REPLACE STAGE RETAIL_STAGE;
LIST @RETAIL_STAGE;

COPY INTO STG_CUSTOMERS FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT=(
TYPE=CSV 
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY='"'
);

COPY INTO STG_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO STG_BRANCHES FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT=(
TYPE=CSV 
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY='"'
);

--CALENDAR
COPY INTO STG_CALENDAR
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO STG_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--CREATE DIM TABLES:CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER(
CUSTOMER_ID INTEGER PRIMARY KEY,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50)
);
INSERT INTO DIM_CUSTOMER 
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP FROM STG_CUSTOMERS;

--DIM PRODUCTS
CREATE OR REPLACE TABLE DIM_PRODUCT(
PRODUCT_ID INTEGER PRIMARY KEY,
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(100),
BRAND VARCHAR(100),
PRICE NUMBER(12,2)
);
INSERT INTO DIM_PRODUCT 
SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,BRAND,PRICE FROM STG_PRODUCTS;

--DIM BRANCH
CREATE OR REPLACE TABLE DIM_BRANCH(
BRANCH_ID INTEGER PRIMARY KEY,
BRANCH_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
REGION VARCHAR(50),
MANAGER_NAME VARCHAR(100)
);
INSERT INTO DIM_BRANCH 
SELECT BRANCH_ID,BRANCH_NAME,CITY,STATE,REGION,MANAGER_NAME FROM STG_BRANCHES;

--DIM DATE
CREATE OR REPLACE TABLE DIM_DATE(
DATE_ID INTEGER PRIMARY KEY,
DATE DATE,
DAY INTEGER,
DAY_NAME VARCHAR(20),
WEEK_NO INTEGER,
MONTH VARCHAR(20),
QUARTER VARCHAR(10),
YEAR INTEGER,
IS_WEEKEND VARCHAR(5)
);
INSERT INTO DIM_DATE 
SELECT DATE_ID,DATE,DAY,DAY_NAME,WEEK_NO,MONTH,QUARTER,YEAR,IS_WEEKEND FROM STG_CALENDAR;

--CREATE FACT_SALES
CREATE OR REPLACE TABLE FACT_SALES(
SALE_ID INTEGER PRIMARY KEY,
CUSTOMER_ID INTEGER,
PRODUCT_ID INTEGER,
BRANCH_ID INTEGER,
DATE_ID INTEGER,
QUANTITY INTEGER,
TOTAL_AMOUNT NUMBER(14,2),
FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
FOREIGN KEY (BRANCH_ID) REFERENCES DIM_BRANCH(BRANCH_ID),
FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
);
INSERT INTO FACT_SALES
SELECT SALE_ID,CUSTOMER_ID,PRODUCT_ID,BRANCH_ID,DATE_ID,QUANTITY,TOTAL_AMOUNT FROM STG_SALES;

--VALIDATE STAR SCHEMA
SELECT COUNT(*) AS CUSTOMER_COUNT FROM DIM_CUSTOMER;
SELECT COUNT(*) AS PRODUCT_COUNT FROM DIM_PRODUCT;
SELECT COUNT(*) AS BRANCH_COUNT FROM DIM_BRANCH;
SELECT COUNT(*) AS DATE_COUNT FROM DIM_DATE;
SELECT COUNT(*) AS SALES_COUNT FROM FACT_SALES;

--CUSTOMER-WISE SALES
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(F.QUANTITY) AS TOTAL_QUANTITY,
SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F JOIN DIM_CUSTOMER C 
ON F.CUSTOMER_ID=C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME 
ORDER BY TOTAL_REVENUE DESC;

--PRODUCT-WISE REVENUE
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(F.QUANTITY) AS TOTAL_QUANTITY,
SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F JOIN DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME 
ORDER BY TOTAL_REVENUE DESC;

--BRANCH-WISE REVENUE
SELECT B.BRANCH_ID,B.BRANCH_NAME,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID GROUP BY B.BRANCH_ID,B.BRANCH_NAME 
ORDER BY TOTAL_REVENUE DESC;

--STATE-WISE REVENUE  
SELECT B.STATE,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID GROUP BY B.STATE 
ORDER BY TOTAL_REVENUE DESC;

--MONTHLY REVENUE
SELECT D.YEAR,D.MONTH,SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID GROUP BY D.YEAR,D.MONTH 
ORDER BY D.YEAR,D.MONTH;

--QUARTERLY REVENUE
SELECT D.YEAR,D.QUARTER,SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID GROUP BY D.YEAR,D.QUARTER 
ORDER BY D.YEAR,D.QUARTER;

--TOP 10 CUSTOMERS 
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_CUSTOMER C ON F.CUSTOMER_ID=C.CUSTOMER_ID GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME 
ORDER BY TOTAL_REVENUE DESC LIMIT 10;

--TOP 10 PRODUCTS
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_PRODUCT P ON F.PRODUCT_ID=P.PRODUCT_ID GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME 
ORDER BY TOTAL_REVENUE DESC LIMIT 10;

--TOP 10 PERFORMING BRANCHES 
SELECT B.BRANCH_ID,B.BRANCH_NAME,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID GROUP BY B.BRANCH_ID,B.BRANCH_NAME 
ORDER BY TOTAL_REVENUE DESC LIMIT 10;

--CATEGORY WISE REVENUE
SELECT P.CATEGORY,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_PRODUCT P ON F.PRODUCT_ID=P.PRODUCT_ID GROUP BY P.CATEGORY 
ORDER BY TOTAL_REVENUE DESC;

--CUSTOMER PURCHASE TREND 
SELECT C.CUSTOMER_NAME,D.DATE,SUM(F.QUANTITY) AS QUANTITY_PURCHASED,
SUM(F.TOTAL_AMOUNT) AS AMOUNT_SPENT FROM FACT_SALES F JOIN DIM_CUSTOMER C 
ON F.CUSTOMER_ID=C.CUSTOMER_ID JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID 
GROUP BY C.CUSTOMER_NAME,D.DATE ORDER BY C.CUSTOMER_NAME,D.DATE;

--PRODUCT PERFORMANCE DASHBOARD QUERY
SELECT P.PRODUCT_NAME,P.CATEGORY,P.BRAND,SUM(F.QUANTITY) AS UNITS_SOLD,
SUM(F.TOTAL_AMOUNT) AS REVENUE,AVG(F.TOTAL_AMOUNT) AS AVG_SALE_VALUE 
FROM FACT_SALES F JOIN DIM_PRODUCT P ON F.PRODUCT_ID=P.PRODUCT_ID 
GROUP BY P.PRODUCT_NAME,P.CATEGORY,P.BRAND ORDER BY REVENUE DESC;

--BRANCH PERFORMANCE DASHBOARD 
SELECT B.BRANCH_NAME,B.STATE,B.REGION,COUNT(F.SALE_ID) AS TOTAL_TRANSACTIONS, 
SUM(F.QUANTITY) AS TOTAL_UNITS,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE 
FROM FACT_SALES F JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID 
GROUP BY B.BRANCH_NAME,B.STATE,B.REGION ORDER BY TOTAL_REVENUE DESC;

--REGIONAL SALES ANALYSIS
SELECT B.REGION,SUM(F.QUANTITY) AS TOTAL_UNITS,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE 
FROM FACT_SALES F JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID 
GROUP BY B.REGION ORDER BY TOTAL_REVENUE DESC;

--SALES TREND ANALYSIS
SELECT D.DATE,SUM(F.QUANTITY) AS TOTAL_UNITS,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE 
FROM FACT_SALES F JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID GROUP BY D.DATE ORDER BY D.DATE;

--VALIDATION QUERY 
SELECT F.SALE_ID,C.CUSTOMER_NAME,P.PRODUCT_NAME,P.CATEGORY,B.BRANCH_NAME,B.STATE,
B.REGION,D.DATE,D.MONTH,D.QUARTER,F.QUANTITY,F.TOTAL_AMOUNT FROM FACT_SALES F 
JOIN DIM_CUSTOMER C ON F.CUSTOMER_ID=C.CUSTOMER_ID JOIN DIM_PRODUCT P 
ON F.PRODUCT_ID=P.PRODUCT_ID JOIN DIM_BRANCH B ON F.BRANCH_ID=B.BRANCH_ID 
JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID ORDER BY F.SALE_ID LIMIT 20;