CREATE DATABASE IF NOT EXISTS RETAIL_DW;
USE DATABASE RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS;
USE SCHEMA RETAIL_ANALYTICS;

SELECT CURRENT_DATABASE(),CURRENT_SCHEMA();

--CREATE SATGE
CREATE OR REPLACE STAGE RETAIL_STAGE;
list @RETAIL_STAGE;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE=CSV 
FIELD_DELIMITER=',' 
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
NULL_IF=('NULL','null','');

--STAGING TABLES
CREATE OR REPLACE TABLE STG_CUSTOMERS(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50)
);
CREATE OR REPLACE TABLE STG_PRODUCTS(
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(100),
BRAND VARCHAR(100),
PRICE NUMBER(12,2)
);
CREATE OR REPLACE TABLE STG_BRANCHES(
BRANCH_ID NUMBER,
BRANCH_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
REGION VARCHAR(50),
MANAGER_NAME VARCHAR(100)
);
CREATE OR REPLACE TABLE STG_CALENDAR(
DATE_ID NUMBER,
DATE_VALUE DATE,
DAY NUMBER,
DAY_NAME VARCHAR(20),
WEEK_NO NUMBER,
MONTH VARCHAR(20),
QUARTER VARCHAR(10),
YEAR NUMBER,
IS_WEEKEND VARCHAR(10)
);
CREATE OR REPLACE TABLE STG_SALES(
SALE_ID NUMBER,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
BRANCH_ID NUMBER,
DATE_ID NUMBER,
QUANTITY NUMBER,
TOTAL_AMOUNT NUMBER(14,2)
);

--LOAD CVS DATA
COPY INTO STG_CUSTOMERS FROM @RETAIL_STAGE/customers.csv 
FILE_FORMAT=(FORMAT_NAME=RETAIL_CSV_FORMAT)
ON_ERROR='CONTINUE';
COPY INTO STG_PRODUCTS FROM @RETAIL_STAGE/products.csv
FILE_FORMAT=(FORMAT_NAME=RETAIL_CSV_FORMAT)
ON_ERROR='CONTINUE';
COPY INTO STG_BRANCHES FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT=(FORMAT_NAME=RETAIL_CSV_FORMAT)
ON_ERROR='CONTINUE';
COPY INTO STG_CALENDAR FROM @RETAIL_STAGE/calendar.csv 
FILE_FORMAT=(FORMAT_NAME=RETAIL_CSV_FORMAT)
ON_ERROR='CONTINUE';
COPY INTO STG_SALES FROM @RETAIL_STAGE/sales.csv 
FILE_FORMAT=(FORMAT_NAME=RETAIL_CSV_FORMAT)
ON_ERROR='CONTINUE';
--VALIDATE STAGING DATA
SELECT COUNT(*) AS CUSTOMER_COUNT FROM STG_CUSTOMERS;
SELECT COUNT(*) AS PRODUCT_COUNT FROM STG_PRODUCTS;
SELECT COUNT(*) AS BRANCH_COUNT FROM STG_BRANCHES;
SELECT COUNT(*) AS DATE_COUNT FROM STG_CALENDAR;
SELECT COUNT(*) AS SALES_COUNT FROM STG_SALES;

--DIMENSION TABLE: DIM_CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER(
CUSTOMER_KEY NUMBER AUTOINCREMENT,
CUSTOMER_ID NUMBER NOT NULL,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50),
CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY)
);
--LOAD DATA
INSERT INTO DIM_CUSTOMER(
CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP 
) SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP FROM STG_CUSTOMERS;
SELECT * FROM DIM_CUSTOMER ORDER BY CUSTOMER_ID;

--DIM PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT(
PRODUCT_KEY NUMBER AUTOINCREMENT,PRODUCT_ID NUMBER NOT NULL,
PRODUCT_NAME VARCHAR(100),
CATEGORY VARCHAR(100),BRAND VARCHAR(100),PRICE NUMBER(12,2),
CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_KEY)
);
INSERT INTO DIM_PRODUCT(
PRODUCT_ID,PRODUCT_NAME,CATEGORY,BRAND,PRICE
) SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,BRAND,PRICE FROM STG_PRODUCTS;
SELECT * FROM DIM_PRODUCT ORDER BY PRODUCT_ID;

--DIM BRANCH
CREATE OR REPLACE TABLE DIM_BRANCH(
BRANCH_KEY NUMBER AUTOINCREMENT,BRANCH_ID NUMBER NOT NULL,BRANCH_NAME VARCHAR(100),
CITY VARCHAR(100),STATE VARCHAR(100),REGION VARCHAR(50),MANAGER_NAME VARCHAR(100),
CONSTRAINT PK_DIM_BRANCH PRIMARY KEY (BRANCH_KEY)
);
INSERT INTO DIM_BRANCH(
BRANCH_ID,BRANCH_NAME,CITY,STATE,REGION,MANAGER_NAME
) SELECT BRANCH_ID,BRANCH_NAME,CITY,STATE,REGION,MANAGER_NAME FROM STG_BRANCHES;
SELECT * FROM DIM_BRANCH ORDER BY BRANCH_ID;

--DIM DATE
CREATE OR REPLACE TABLE DIM_DATE(
DATE_KEY NUMBER AUTOINCREMENT,DATE_ID NUMBER NOT NULL,DATE_VALUE DATE,DAY NUMBER,
DAY_NAME VARCHAR(20),WEEK_NO NUMBER,MONTH VARCHAR(20),QUARTER VARCHAR(10),
YEAR NUMBER,IS_WEEKEND VARCHAR(10),
CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);
INSERT INTO DIM_DATE(
DATE_ID,DATE_VALUE,DAY,DAY_NAME,WEEK_NO,MONTH,QUARTER,YEAR,IS_WEEKEND
) SELECT DATE_ID,DATE_VALUE,DAY,DAY_NAME,WEEK_NO,MONTH,QUARTER,YEAR,IS_WEEKEND
FROM STG_CALENDAR;
SELECT * FROM DIM_DATE ORDER BY DATE_ID;

--FACT SALES 
CREATE OR REPLACE TABLE FACT_SALES(
SALE_ID NUMBER NOT NULL,CUSTOMER_KEY NUMBER NOT NULL,PRODUCT_KEY NUMBER NOT NULL,
BRANCH_KEY NUMBER NOT NULL,DATE_KEY NUMBER NOT NULL,QUANTITY NUMBER NOT NULL,
TOTAL_AMOUNT NUMBER(14,2) NOT NULL,
CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALE_ID)
);
INSERT INTO FACT_SALES(
SALE_ID,CUSTOMER_KEY,PRODUCT_KEY,BRANCH_KEY,DATE_KEY,QUANTITY,TOTAL_AMOUNT 
) SELECT S.SALE_ID,C.CUSTOMER_KEY,P.PRODUCT_KEY,B.BRANCH_KEY,D.DATE_KEY,
S.QUANTITY,S.TOTAL_AMOUNT FROM STG_SALES S JOIN DIM_CUSTOMER C 
ON S.CUSTOMER_ID=C.CUSTOMER_ID JOIN DIM_PRODUCT P ON S.PRODUCT_ID=P.PRODUCT_ID
JOIN DIM_BRANCH B ON S.BRANCH_ID=B.BRANCH_ID JOIN DIM_DATE D ON S.DATE_ID=D.DATE_ID;
SELECT * FROM FACT_SALES ORDER BY SALE_ID LIMIT 20;

--CHECK FOR DUPLICATE SALE IDS
SELECT SALE_ID,COUNT(*) AS CNT FROM FACT_SALES GROUP BY SALE_ID HAVING COUNT(*)>1;

--VALIDATE ORPHAN RECORDS
SELECT COUNT(*) AS ORPHAN_CUSTOMERS FROM FACT_SALES F LEFT JOIN DIM_CUSTOMER C 
ON F.CUSTOMER_KEY=C.CUSTOMER_KEY WHERE C.CUSTOMER_KEY IS NULL;
--PRODUCT
SELECT COUNT(*) AS ORPHAN_PRODUCTS FROM FACT_SALES F LEFT JOIN DIM_PRODUCT P 
ON F.PRODUCT_KEY=P.PRODUCT_KEY WHERE P.PRODUCT_KEY IS NULL;
--BRANCH
SELECT COUNT(*) AS ORPHAN_BRANCHES FROM FACT_SALES F LEFT JOIN DIM_BRANCH B 
ON F.BRANCH_KEY=B.BRANCH_KEY WHERE B.BRANCH_KEY IS NULL;
--DATE
SELECT COUNT(*) AS ORPHAN_DATES FROM FACT_SALES F LEFT JOIN DIM_DATE D 
ON F.DATE_KEY=D.DATE_KEY WHERE D.DATE_KEY IS NULL;

--TOTAL REVENUE
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY,SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES;

--CUSTOMER REVENUE REPORT
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.MEMBERSHIP,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE 
FROM FACT_SALES F JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY 
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME,C.MEMBERSHIP ORDER BY TOTAL_REVENUE DESC;

--PRODUCT REVENUE REPORT
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,P.BRAND,SUM(F.QUANTITY) AS TOTAL_QUANTITY,
SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F JOIN DIM_PRODUCT P 
ON F.PRODUCT_KEY=P.PRODUCT_KEY GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,
P.BRAND ORDER BY TOTAL_REVENUE DESC;

--BRANCH PERFORMANCE
SELECT B.BRANCH_ID,B.BRANCH_NAME,B.CITY,B.STATE,B.REGION,SUM(F.QUANTITY) AS TOTAL_QUANTITY,
SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES FROM FACT_SALES F JOIN DIM_BRANCH B 
ON F.BRANCH_KEY=B.BRANCH_KEY GROUP BY B.BRANCH_ID,B.BRANCH_NAME,B.CITY,B.STATE,
B.REGION ORDER BY TOTAL_SALES DESC;

--MONTHLY REVENUE
SELECT D.YEAR,D.MONTH,SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_KEY=D.DATE_KEY GROUP BY D.YEAR,D.MONTH ORDER BY D.YEAR,
MIN(D.DATE_VALUE);

--STATE WISE SALES
SELECT C.STATE,SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES FROM FACT_SALES F 
JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY GROUP BY C.STATE 
ORDER BY TOTAL_SALES DESC;

--CATEGORY WISE REVENUE
SELECT P.CATEGORY,SUM(F.QUANTITY) AS TOTAL_QUANTITY,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_PRODUCT P ON F.PRODUCT_KEY=P.PRODUCT_KEY GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

--TOP 10 CUSTOMERS
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES FROM FACT_SALES F 
JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC LIMIT 10;

--TOP 10 PRODUCTS
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_PRODUCT P ON F.PRODUCT_KEY=P.PRODUCT_KEY GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY 
ORDER BY TOTAL_REVENUE DESC LIMIT 10;

--SALES TREND ANALYSIS
SELECT D.DATE_VALUE,SUM(F.TOTAL_AMOUNT) AS DAILY_SALES FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_KEY=D.DATE_KEY GROUP BY D.DATE_VALUE ORDER BY D.DATE_VALUE;

--QUARTERLY REVENUE 
SELECT D.YEAR,D.QUARTER,SUM(F.TOTAL_AMOUNT) AS QUARTERY_REVENUE FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_KEY=D.DATE_KEY GROUP BY D.YEAR,D.QUARTER 
ORDER BY D.YEAR,D.QUARTER;

--MEMBERSHIP-WISE REVENUE 
SELECT C.MEMBERSHIP,COUNT(DISTINCT C.CUSTOMER_ID) AS CUSTOMER_COUNT,
SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY GROUP BY C.MEMBERSHIP 
ORDER BY TOTAL_REVENUE DESC;

--REGION WISE REVENUE
SELECT B.REGION,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_BRANCH B ON F.BRANCH_KEY=B.BRANCH_KEY GROUP BY B.REGION 
ORDER BY TOTAL_REVENUE DESC; 

--WEEKEND VS WEEKDAY SALES
SELECT D.IS_WEEKEND,SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES,SUM(F.QUANTITY) AS TOTAL_QUANTITY FROM FACT_SALES F 
JOIN DIM_DATE D ON F.DATE_KEY=D.DATE_KEY GROUP BY D.IS_WEEKEND 
ORDER BY TOTAL_SALES DESC;

--AVG TRANSACTION VALUE
SELECT AVG(TOTAL_AMOUNT) AS AVERAGE_TRANSACTION_VALUE FROM FACT_SALES;

--PRODUCT CATEGORY+BRANCH ANALYSIS
SELECT B.BRANCH_NAME,P.CATEGORY,SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES F 
JOIN DIM_BRANCH B ON F.BRANCH_KEY=B.BRANCH_KEY JOIN DIM_PRODUCT P 
ON F.PRODUCT_KEY=P.PRODUCT_KEY GROUP BY B.BRANCH_NAME,P.CATEGORY 
ORDER BY B.BRANCH_NAME,TOTAL_REVENUE DESC;

--CHECK THE GRAIN 
SELECT F.SALE_ID,C.CUSTOMER_NAME,P.PRODUCT_NAME,B.BRANCH_NAME,D.DATE_VALUE,F.QUANTITY,
F.TOTAL_AMOUNT FROM FACT_SALES F JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY 
JOIN DIM_PRODUCT P ON F.PRODUCT_KEY=P.PRODUCT_KEY JOIN DIM_BRANCH B ON 
F.BRANCH_KEY=B.BRANCH_KEY JOIN DIM_DATE D ON F.DATE_KEY=D.DATE_KEY 
ORDER BY F.SALE_ID LIMIT 20;

--SHOW TABLE STRUCTURE
DESC TABLE DIM_CUSTOMER;
DESC TABLE DIM_PRODUCT;
DESC TABLE DIM_BRANCH;
DESC TABLE DIM_DATE;
DESC TABLE FACT_SALES;

--SHOW COMPLETE MODEL
SHOW TABLES;

--VALIDATION SCRIPT
SELECT 'STG_CUSTOMERS' AS TABLE_NAME,COUNT(*) AS ROW_COUNT FROM STG_CUSTOMERS 
UNION ALL SELECT 'STG_PRODUCTS',COUNT(*) FROM STG_PRODUCTS 
UNION ALL SELECT 'STG_BRANCHES',COUNT(*) FROM STG_BRANCHES 
UNION ALL SELECT 'STG_CALENDAR',COUNT(*) FROM STG_CALENDAR 
UNION ALL SELECT 'STG_SALES',COUNT(*) FROM STG_SALES
UNION ALL SELECT 'DIM_CUSTOMER',COUNT(*) FROM DIM_CUSTOMER 
UNION ALL SELECT 'DIM_PRODUCT',COUNT(*) FROM DIM_PRODUCT
UNION ALL SELECT 'DIM_BRANCH',COUNT(*) FROM DIM_BRANCH
UNION ALL SELECT 'DIM_DATE',COUNT(*) FROM DIM_DATE
UNION ALL SELECT 'FACT_SALES',COUNT(*) FROM FACT_SALES;