--CREATE DATABASE AND SCHEMA 
CREATE OR REPLACE DATABASE CUSTOMER_SCD_DB;
USE DATABASE CUSTOMER_SCD_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_ANALYTICS;
USE SCHEMA CUSTOMER_ANALYTICS;

--CREATE DIMENSION
CREATE OR REPLACE TABLE DIM_CUSTOMER(
CUSTOMER_KEY NUMBER AUTOINCREMENT,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50),
SEGMENT VARCHAR(50)
);

--CREATE STAGE 
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
LIST @CUSTOMER_STAGE;

--FILE FORMAT 
CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT 
TYPE=CSV 
SKIP_HEADER=1 
FIELD_OPTIONALLY_ENCLOSED_BY='"';

--LOAD DATA
COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

--CREATE TABLE
CREATE OR REPLACE TABLE CUSTOMER_UPDATES(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
MEMBERSHIP VARCHAR(50),
SEGMENT VARCHAR(50)
);
LIST @CUSTOMER_STAGE;
COPY INTO CUSTOMER_UPDATES FROM @CUSTOMER_STAGE/customer_updates.csv 
FILE_FORMAT=CUSTOMER_CSV_FORMAT;

-- IDENTIFY CHANGED CUSTOMERS
SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY
   OR d.STATE <> u.STATE
   OR d.MEMBERSHIP <> u.MEMBERSHIP
   OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

--ATTRIBUTE-LEVEL CHANGE REPORT 
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

ORDER BY CUSTOMER_ID, ATTRIBUTE;

--SCD PROBLEM 
--BEFORE UPDATE 
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT FROM DIM_CUSTOMER 
WHERE CUSTOMER_ID=101;
-- OVERWRITE EXISTING DIMENSION 
UPDATE DIM_CUSTOMER d SET CITY=u.CITY,STATE=u.STATE,MEMBERSHIP=u.MEMBERSHIP,
SEGMENT=u.SEGMENT FROM CUSTOMER_UPDATES u WHERE d.CUSTOMER_ID=u.CUSTOMER_ID;

--DISPLAY UPDATED DIMENSION 
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP,SEGMENT FROM DIM_CUSTOMER 
ORDER BY CUSTOMER_ID;

--PROOF OF HISTORICAL DATA LOSS
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP FROM DIM_CUSTOMER 
WHERE CUSTOMER_ID=101;

--BUSINESS IMPACT ANALYSIS 
SELECT CUSTOMER_ID,CUSTOMER_NAME,'Hyderabad' AS HISTORICAL_CITY,CITY AS CURRENT_CITY,
'Telangana' AS HISTORICAL_STATE,STATE AS CURRENT_STATE,'Sliver' AS HISTORICAL_MEMBERSHIP,
MEMBERSHIP AS CURRENT_MEMBERSHIP FROM DIM_CUSTOMER WHERE CUSTOMER_ID=101;

--ACTUAL DATA IN DIMENSION TABLE 
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP FROM DIM_CUSTOMER 
WHERE CUSTOMER_ID=101;