-- CREATE DATABASE AND SCHEMA 
CREATE OR REPLACE DATABASE RETAIL_DW;
USE DATABASE RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS;
USE SCHEMA SALES_ANALYTICS;

--CREATE DIM_STORE 
CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);
DESC TABLE DIM_STORE;

--CREATE DIM_PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);
DESC TABLE DIM_PRODUCT;

--CREATE STAGE 
CREATE OR REPLACE STAGE RETAIL_STAGE;

--CREATE DIM_CUSTOMER_HYBRID
CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);
DESC TABLE DIM_CUSTOMER_HYBRID;

--FILE FORMAT 
CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

LIST @RETAIL_STAGE;

--LOAD DATA
COPY INTO DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
FROM @RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT
PATTERN = '.*stores[.]csv'
ON_ERROR = 'ABORT_STATEMENT';
SELECT *
FROM DIM_STORE
ORDER BY STORE_ID;

COPY INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
FROM @RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT
PATTERN = '.*products[.]csv'
ON_ERROR = 'ABORT_STATEMENT';
SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;

COPY INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
FROM (
    SELECT
        $1::NUMBER,
        $2::VARCHAR,
        $3::VARCHAR,
        NULL::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        NULL::VARCHAR,
        $5::VARCHAR,
        $6::VARCHAR,
        '2026-01-01'::DATE,
        '9999-12-31'::DATE,
        TRUE
    FROM @RETAIL_STAGE
)
FILE_FORMAT = RETAIL_CSV_FORMAT
PATTERN = '.*customers_initial[.]csv'
ON_ERROR = 'ABORT_STATEMENT';
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

--CREATE FACT_SALES
CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_FACT_CUSTOMER
        FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    CONSTRAINT FK_FACT_STORE
        FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    CONSTRAINT FK_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);
DESC TABLE FACT_SALES;
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 501
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;
SELECT *
FROM FACT_SALES
WHERE TRANSACTION_ID = 'TXN-1001';
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    2,
    p.UNIT_PRICE,
    2 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 203
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 502
WHERE c.CUSTOMER_ID = 103
  AND c.IS_CURRENT = TRUE;
SELECT
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
FROM FACT_SALES
ORDER BY TRANSACTION_DATE;

-- SCD TYPE1
UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201
  AND STORE_NAME = 'Metro Flagship';
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

--MULTI ATTRIBUTE UPDATE 
UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;
UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;
UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;
SELECT
    CUSTOMER_ID,
    CITY,
    CURRENT_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TEMP TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);
COPY INTO STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
)
FROM @RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT
PATTERN = '.*customer_updates[.]csv'
ON_ERROR = 'ABORT_STATEMENT';
SELECT *
FROM STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    old.CITY AS PREVIOUS_CITY,
    u.STATE,
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID old
    ON u.CUSTOMER_ID = old.CUSTOMER_ID
   AND old.IS_CURRENT = FALSE
   AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Bengaluru',
    STATE = 'Karnataka',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;
UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Chennai',
    STATE = 'Tamil Nadu',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;
UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Hyderabad',
    STATE = 'Telangana',
    CURRENT_MEMBERSHIP = 'Platinum',
    PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;
SELECT
    CUSTOMER_ID,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 503
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;
SELECT
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
FROM FACT_SALES
ORDER BY TRANSACTION_DATE;
SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    f.CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.SEGMENT,
    c.HISTORICAL_MEMBERSHIP,
    c.IS_CURRENT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;
SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.UNIT_PRICE,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;

SELECT 'DIM_STORE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM DIM_STORE

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_CUSTOMER_HYBRID', COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT 'CURRENT_CUSTOMERS', COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT 'HISTORICAL_CUSTOMERS', COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT 'FACT_SALES_TRANSACTIONS', COUNT(*)
FROM FACT_SALES;